// --- DATI ITALIANI (data-it.js) ---

// 1. TESTI UI (Per il multilingua)
const TEXTS = {
    title: "MAPTOPIA IT",
    enterBtn: "✨ ENTRA NELLA MAPPA ✨",
    menu: {
        pnj: "NPC",
        animals: "ANIMALI",
        bus: "BUS",
        shops: "NEGOZI",
        places: "LUOGHI",
        fish: "PESCI",
        bugs: "INSETTI",
        birds: "UCCELLI",
        resources: "RISORSE"
    },
    chat: {
        success: "✅ Messaggio inviato con successo!",
        error: "❌ Errore durante l'invio.",
        incomplete: "⚠️ Compila tutti i campi.",
        wait: "Invio in corso..."
    },
    quiz: {
        success: "✅ BRAVO!",
        error: "❌ ERRORE!",
        finishTitle: "🏆 ESPERTO CONFERMATO!",
        finishText: "Conosci Heartopia come le tue tasche.",
        quitBtn: "ESCI DAL QUIZ"
    },
    like: {
        thankyou: "GRAZIE!",
        already: "Hai già votato!"
    }
};

// 2. LISTA DEGLI NPC
const PNJ_DATA = [
    [-471, 501, "Bob", "pnj/bob.png"],
    [-526, 499, "Atara", "pnj/atara.png"],
    [-478, 493, "Collezionista", "pnj/collectioneur.png"],
    [-469, 488, "Dorothée", "pnj/dorothée.png"],
    [-446, 493, "Massimo", "pnj/massimo.png"],
    [-412, 418, "Ka Ching", "pnj/ka ching.png"],
    [-399, 591, "Andrew", "pnj/andrew.png"],
    [-259, 522, "Eric", "pnj/eric.png"],
    [-456, 549, "Vanya", "pnj/vanya.png"],
    [-502, 582, "Naniwa", "pnj/naniwa.png"],
    [-502, 519, "Sig.ra Joan", "pnj/mme joan.png"],
    [-807, 419, "Will", "pnj/will.png"],
    [-355, 809, "Patti", "pnj/patti.png"],
    [-653, 225, "Vernie", "pnj/vernie.png"],
    [-498, 526, "Bailey j", "pnj/bayleyj.png"],
    [-528.3, 560.3, "Blanc", "pnj/blanc.png"],
    [-499.8, 499.0, "Annie", "pnj/annie.png"],
    [-532.4, 634.8, "Albert Jr.", "pnj/albert jr.png"],
    [-734.8, 445.8, "Bill", "pnj/bill.png"]
];

// 3. BUS
const BUS_DATA = [
    ["Periferia Ovest",[-533,340]], ["Periferia Villaggio",[-519,639]], ["Villaggio Pescatori",[-654,479]], 
    ["Campo di Fiori",[-532,218]], ["Montagna Termale",[-222,512]], ["Periferia Nord",[-373,480]], 
    ["Piazza Centrale",[-497,481]], ["Foresta",[-500,798]]
];

// 4. NEGOZI
const SHOP_DATA = [
    [-472,487,"Abbigliamento","vetement.png"],[-474,503,"Mobili","Meuble.png"],
    [-496.4,520.6,"Animali","chien.png"],[-440,467,"Libreria","Librairie.png"]
];

// 5. ANIMALI
const ANIMAL_DATA = [
    {pos: [-691, 783], name: "Panda", img: "panda.png", radius: 60},
    {pos: [-184, 291], name: "Capibara", img: "capybara.png", radius: 50},
    {pos: [-533, 340], name: "Coniglio", img: "lapin.png", radius: 40},
    {pos: [-649, 185], name: "Volpe", img: "renard.png", radius: 70},
    {pos: [-737, 512], name: "Lontra", img: "loutre.png", radius: 40},
    {pos: [-354.3, 277.3], name: "Visone", img: "vison.png", radius: 10},
    {pos: [-531, 805], name: "Cervo", img: "cerf.png", radius: 60},
    {pos: [-725, 208], name: "Lama", img: "lama.png", radius: 50}
];

// 6. LUOGHI
const LIEUX_DATA = [
    {pos:[-538,492], name:"Piazza Centrale", type:"label-ville", startOn:true}, 
    {pos:[-692,506], name:"Villaggio Pescatori", type:"label-ville", startOn:true}, 
    {pos:[-438,513], name:"Via degli Abitanti", type:"label-ville", startOn:true}, 
    {pos:[-649,185], name:"Campo di Fiori", type:"label-ville", startOn:true}, 
    {pos:[-440,184], name:"Montagna della Balena", type:"label-ville", startOn:true}, 
    {pos:[-184,291], name:"Le Rovine", type:"label-ville", startOn:true}, 
    {pos:[-223,501], name:"Montagna Termale", type:"label-ville", startOn:true}, 
    {pos:[-228,627], name:"Scogliera Rocciosa", type:"label-ville", startOn:true}, 
    {pos:[-531,805], name:"Foresta di Querce", type:"label-ville", startOn:true}, 
    {pos:[-494,429], name:"Via delle Arti", type:"label-ville", startOn:true}, 
    {pos:[-510,558], name:"Via dei Giardini", type:"label-ville", startOn:true}, 
    {pos:[-736,602], name:"Molo Orientale", type:"label-ville", startOn:true}, 
    {pos:[-690,402], name:"Il Molo", type:"label-ville", startOn:true}, 
    {pos:[-780,387], name:"Faro", type:"label-ville", startOn:true}, 
    {pos:[-691,783], name:"Trampolino", type:"label-ville", startOn:true}, 
    {pos:[-338,933], name:"Isola della Foresta", type:"label-ville", startOn:true}, 
    {pos:[-587,406], name:"Periferia", type:"label-ville", startOn:true}, 
    {pos:[-725,208], name:"Spiaggia Viola", type:"label-ville", startOn:true}, 
    {pos:[-783,478], name:"Mare Calmo", type:"label-eau", startOn:true}, 
    {pos:[-534,92], name:"Mare della Balena", type:"label-eau", startOn:true}, 
    {pos:[-68,497], name:"Mare Antico", type:"label-eau", startOn:true}, 
    {pos:[-536,232], name:"Lago della Prateria", type:"label-eau", startOn:true}, 
    {pos:[-337,319], name:"Fiume Aurora", type:"label-eau", startOn:true}, 
    {pos:[-176,394], name:"Lago Vulcanico", type:"label-eau", startOn:true}, 
    {pos:[-265,537], name:"Lago Termale", type:"label-eau", startOn:true}, 
    {pos:[-344,652], name:"Fiume Basso", type:"label-eau", startOn:true}, 
    {pos:[-598,748], name:"Lago della Foresta", type:"label-eau", startOn:true}, 
    {pos:[-431,774], name:"Lago Alto della Foresta", type:"label-eau", startOn:true}, 
    {pos:[-608,481], name:"Lago di Periferia", type:"label-eau", startOn:true}, 
    {pos:[-669,368], name:"Fiume Tranquillo", type:"label-eau", startOn:true}, 
    {pos:[-674,627], name:"Fiume Alberi Giganti", type:"label-eau", startOn:true}, 
    {pos:[-600,600], name:"Campo di Fiori al Mulino", type:"label-ville", startOn:true}, 
    {pos:[-670,450], name:"Pontile Est", type:"label-ville", startOn:true}
];

// 7. RISORSE
const resourcesData = {
    "Lampone": { icon: "resource/framboise.png", positions: [[-680.8, 330.9], [-668.5, 352.1], [-667.9, 268.5], [-648.3, 288.6], [-613.5, 317.4], [-602.8, 274.5], [-617.6, 211.6], [-571.5, 254.4], [-538.9, 208.6], [-527.8, 251.6], [-535.8, 288.3], [-503.1, 242.9], [-495, 222.4], [-453.8, 222.4], [-438.6, 246], [-395, 247.4], [-387.1, 269.5]] },
    "Mirtillo": { icon: "resource/myrtille.png", positions: [[-642.9, 371.9], [-631.9, 368.4], [-628.5, 365.5], [-606.8, 350.3], [-602.5, 342.3], [-590.1, 334.1], [-575.6, 332.1], [-562.1, 330], [-544.9, 324.5], [-518.4, 320.3], [-515.9, 320.5], [-500.8, 321.1], [-479.3, 328.6], [-468.3, 320], [-437.3, 313.9], [-411.4, 311.4], [-400.3, 311.4], [-379.5, 304.1], [-327.4, 352], [-313.6, 339], [-328.6, 371.5], [-324.4, 389.3], [-297.9, 410.8], [-271.6, 395.4], [-319.9, 413.5], [-330.4, 421.6], [-333.4, 450], [-338.6, 468.6], [-297.4, 484.4], [-349, 489.4], [-356.5, 499.3], [-360.4, 526.4], [-355.5, 545.1], [-352.9, 565.9], [-316, 558.1], [-363.6, 578.4], [-365.3, 609], [-360.9, 628.1], [-343, 634], [-388, 655.4], [-400.9, 654.3], [-421.9, 656.4], [-444.1, 670.6], [-462.5, 654], [-476.8, 654.6], [-491.6, 656.3], [-506.4, 672.4], [-525.4, 688], [-542.6, 650], [-559.3, 644.9], [-575.6, 651], [-597.8, 643.8], [-604.8, 633.8], [-627.9, 619.4]] },
    "Mela": { icon: "resource/pomme.png", positions: [[-356.3, 493], [-365.4, 560.1], [-362.4, 581], [-324.6, 570.1], [-296, 610.3], [-365.6, 619.5], [-362.8, 628.5], [-393.5, 654.8], [-420.6, 653.3], [-436.1, 665.4], [-444.4, 685.1], [-436.6, 697.5], [-458.4, 744.9], [-505, 677.3], [-494.5, 657], [-459.8, 653.6], [-530.1, 677.9], [-540.1, 648.6], [-592.8, 676.6], [-606.9, 634.1], [-629.3, 623]] },
    "Grande Albero": { icon: "resource/grand arbre.png", positions: [[-612, 424.5], [-641.8, 369], [-351, 329.5], [-414.3, 337.1], [-396.3, 608.9], [-376.3, 624], [-616, 593.6], [-672.3, 642]] },
    "Legno di Quercia Scivoloso": { icon: "resource/bois de chaine glissant.png", positions: [[-532, 787.3]] },
    "Pietra": { icon: "resource/pierre.png", positions: [[-615.9, 316], [-641.5, 278.8], [-558.4, 257.4], [-535, 292], [-499.5, 241.1], [-466.8, 283.1], [-407.1, 244.1], [-284, 402.8], [-254.6, 367.9], [-309.4, 479.1], [-263, 466.6], [-289.1, 544.6], [-315.5, 567.9], [-298.6, 625.4], [-391.3, 726.9], [-443.6, 697], [-468.6, 733.8], [-519, 714.9], [-564.9, 732.8], [-605.1, 680.3], [-673.9, 684.1]] },
    "Fluorite": { icon: "resource/fluorite.png", positions: [[-417.8, 313.8]] },
    "Arancia": { icon: "resource/orange.png", positions: [[-650.1, 370.9], [-639.5, 372], [-607.3, 351.4], [-602.9, 343.5], [-588.6, 336.6], [-559.6, 329.5], [-542.1, 324.8], [-515, 319.5], [-470.5, 321], [-461.4, 271.5], [-410.8, 314], [-397.3, 310.1], [-310.9, 339.3], [-327.6, 373.9], [-324.9, 391.9], [-295.4, 411.1], [-330.4, 420.9], [-333.8, 452.9]] }
};

// 8. PESCI
const fishList = [
    {name:"Alborella", bg:"condition/ablette_lieu.png", cond:"condition/ablette_meteo.png", heure:"condition/ablette_heure.png"},
    {name:"Acantharchus pomotis", bg:"condition/acantharchus_pomotis_lieu.png", cond:"condition/acantharchus_pomotis_meteo.png", heure:"condition/acantharchus_pomotis_heure.png"},
    {name:"Anguilla europea", bg:"condition/anguille_europeenne_lieu.png", cond:"condition/anguille_europeenne_meteo.png", heure:"condition/anguille_europeenne_heure.png"},
    {name:"Aphyosemion striatum", bg:"condition/aphyosemion_striatum_lieu.png", cond:"condition/aphyosemion_striatum_meteo.png", heure:"condition/aphyosemion_striatum_heure.png"},
    {name:"Barbo", bg:"condition/barbeau_lieu.png", cond:"condition/barbeau_meteo.png", heure:"condition/barbeau_heure.png"},
    {name:"Barbiglio", bg:"condition/barbillon_lieu.png", cond:"condition/barbillon_meteo.png", heure:"condition/barbillon_heure.png"},
    {name:"Rana pescatrice", bg:"condition/baudroie_lieu.png", cond:"condition/baudroie_meteo.png", heure:"condition/baudroie_heure.png"},
    {name:"Paguro bernardo", bg:"condition/bernard_lhermite_lieu.png", cond:"condition/bernard_lhermite_meteo.png", heure:"condition/bernard_lhermite_heure.png"},
    {name:"Bavosa di fiume", bg:"condition/blennie_de_riviere_lieu.png", cond:"condition/blennie_de_riviere_meteo.png", heure:"condition/blennie_de_riviere_heure.png"},
    {name:"Palamita", bg:"condition/bonite_lieu.png", cond:"condition/bonite_meteo.png", heure:"condition/bonite_heure.png"},
    {name:"Luccio maculato", bg:"condition/brochet_tachete_lieu.png", cond:"condition/brochet_tachete_meteo.png", heure:"condition/brochet_tachete_heure.png"},
    {name:"Carpa argentata", bg:"condition/carpe_argente_lieu.png", cond:"condition/carpe_argente_meteo.png", heure:"condition/carpe_argente_heure.png"},
    {name:"Carpa europea", bg:"condition/carpe_europeenne_lieu.png", cond:"condition/carpe_europeenne_meteo.png", heure:"condition/carpe_europeenne_heure.png"},
    {name:"Carpa farfalla", bg:"condition/carpe_papillon_lieu.png", cond:"condition/carpe_papillon_meteo.png", heure:"condition/carpe_papillon_heure.png"},
    {name:"Carpa nera", bg:"condition/carpe_noire_lieu.png", cond:"condition/carpe_noire_meteo.png", heure:"condition/carpe_noire_heure.png"},
    {name:"Scazzone", bg:"condition/chabot_lieu.png", cond:"condition/chabot_meteo.png", heure:"condition/chabot_heure.png"},
    {name:"Chimera d'argento", bg:"condition/chimere_argentee_lieu.png", cond:"condition/chimere_argentee_meteo.png", heure:"condition/chimere_argentee_heure.png"},
    {name:"Cometa", bg:"condition/comete_coussut_lieu.png", cond:"condition/comete_coussut_meteo.png", heure:"condition/comete_coussut_heure.png"},
    {name:"Granchio di fiume", bg:"condition/crabe_de_ruisseau_lieu.png", cond:"condition/crabe_de_ruisseau_meteo.png", heure:"condition/crabe_de_ruisseau_heure.png"},
    {name:"Gamberetto di mare", bg:"condition/crevette_de_la_mer_lieu.png", cond:"condition/crevette_de_la_mer_meteo.png", heure:"condition/crevette_de_la_mer_heure.png"},
    {name:"Gamberetto verde", bg:"condition/crevette_verte_lieu.png", cond:"condition/crevette_verte_meteo.png", heure:"condition/crevette_verte_heure.png"},
    {name:"Gambero nobile", bg:"condition/ecrevisse_noble_lieu.png", cond:"condition/ecrevisse_noble_meteo.png", heure:"condition/ecrevisse_noble_heure.png"},
    {name:"Gambero nobile blu", bg:"condition/ecrevisse_noble_bleue_lieu.png", cond:"condition/ecrevisse_noble_bleue_meteo.png", heure:"condition/ecrevisse_noble_bleue_heure.png"},
    {name:"Eglefino", bg:"condition/eglefin_lieu.png", cond:"condition/eglefin_meteo.png", heure:"condition/eglefin_heure.png"},
    {name:"Sperlano", bg:"condition/eperlan_lieu.png", cond:"condition/eperlan_meteo.png", heure:"condition/eperlan_heure.png"},
    {name:"Coregone", bg:"condition/fera_lieu.png", cond:"condition/fera_meteo.png", heure:"condition/fera_heure.png"},
    {name:"Persico trota grande", bg:"condition/grand_blackbasse_lieu.png", cond:"condition/grand_blackbasse_meteo.png", heure:"condition/grand_blackbasse_heure.png"},
    {name:"Rana europea", bg:"condition/grenouille_europeenne_lieu.png", cond:"condition/grenouille_europeenne_meteo.png", heure:"condition/grenouille_europeenne_heure.png"},
    {name:"Ghiozzo", bg:"condition/gobie_lieu.png", cond:"condition/gobie_meteo.png", heure:"condition/gobie_heure.png"},
    {name:"Capone gallinella", bg:"condition/grondin_perlon_lieu.png", cond:"condition/grondin_perlon_meteo.png", heure:"condition/grondin_perlon_heure.png"},
    {name:"Cavalluccio marino", bg:"condition/hippocampe_lieu.png", cond:"condition/hippocampe_meteo.png", heure:"condition/hippocampe_heure.png"},
    {name:"Salmone del Danubio", bg:"condition/huchon_lieu.png", cond:"condition/huchon_meteo.png", heure:"condition/huchon_heure.png"},
    {name:"Aragosta europea", bg:"condition/langouste_europeenne_lieu.png", cond:"condition/langouste_europeenne_meteo.png", heure:"condition/langouste_europeenne_heure.png"},
    {name:"Cobite dei fiori", bg:"condition/loche_des_fleurs_lieu.png", cond:"condition/loche_des_fleurs_meteo.png", heure:"condition/loche_des_fleurs_heure.png"},
    {name:"Cobite di roccia", bg:"condition/loche_des_rochers_lieu.png", cond:"condition/loche_des_rochers_meteo.png", heure:"condition/loche_des_rochers_heure.png"},
    {name:"Bottatrice", bg:"condition/lotte_lieu.png", cond:"condition/lotte_meteo.png", heure:"condition/lotte_heure.png"},
    {name:"Sgombro atlantico", bg:"condition/maquereau_atlantique_lieu.png", cond:"condition/maquereau_atlantique_meteo.png", heure:"condition/maquereau_atlantique_heure.png"},
    {name:"Cozza", bg:"condition/moule_lieu.png", cond:"condition/moule_meteo.png", heure:"condition/moule_heure.png"},
    {name:"Salmerino alpino", bg:"condition/omble_chevalier_lieu.png", cond:"condition/omble_chevalier_meteo.png", heure:"condition/omble_chevalier_heure.png"},
    {name:"Ombrina", bg:"condition/ombrine_lieu.png", cond:"condition/ombrine_meteo.png", heure:"condition/ombrine_heure.png"},
    {name:"Pagello", bg:"condition/pagellus_bogaraveo_lieu.png", cond:"condition/pagellus_bogaraveo_meteo.png", heure:"condition/pagellus_bogaraveo_heure.png"},
    {name:"Pesce persico di mare", bg:"condition/perche_de_mer_lieu.png", cond:"condition/perche_de_mer_meteo.png", heure:"condition/perche_de_mer_heure.png"},
    {name:"Pesce persico prugna", bg:"condition/perche_de_prunier_lieu.png", cond:"condition/perche_de_prunier_meteo.png", heure:"condition/perche_de_prunier_heure.png"},
    {name:"Pesce persico di fiume", bg:"condition/perche_de_riviere_lieu.png", cond:"condition/perche_de_riviere_meteo.png", heure:"condition/perche_de_riviere_heure.png"},
    {name:"Polpo", bg:"condition/pieuvre_lieu.png", cond:"condition/pieuvre_meteo.png", heure:"condition/pieuvre_heure.png"},
    {name:"Polpo nano atlantico", bg:"condition/pieuvre_naine_atlantique_lieu.png", cond:"condition/pieuvre_naine_atlantique_meteo.png", heure:"condition/pieuvre_naine_atlantique_heure.png"},
    {name:"Pesce tigre", bg:"condition/poissontigre_a_ventre_rouge_lieu.png", cond:"condition/poissontigre_a_ventre_rouge_meteo.png", heure:"condition/poissontigre_a_ventre_rouge_heure.png"},
    {name:"Platessa europea", bg:"condition/plie_europeenne_lieu.png", cond:"condition/plie_europeenne_meteo.png", heure:"condition/plie_europeenne_heure.png"},
    {name:"Pesce pagliaccio", bg:"condition/poissonclown_lieu.png", cond:"condition/poissonclown_meteo.png", heure:"condition/poissonclown_heure.png"},
    {name:"Spinarello", bg:"condition/poisson_epineux_lieu.png", cond:"condition/poisson_epineux_meteo.png", heure:"condition/poisson_epineux_heure.png"},
    {name:"Pesce palla di fiume", bg:"condition/poissonglobe_de_riviere_lieu.png", cond:"condition/poissonglobe_de_riviere_meteo.png", heure:"condition/poissonglobe_de_riviere_heure.png"},
    {name:"Pesce rosso", bg:"condition/poisson_rouge_lieu.png", cond:"condition/poisson_rouge_meteo.png", heure:"condition/poisson_rouge_heure.png"},
    {name:"Pesce nastro", bg:"condition/poisson_ruban_lieu.png", cond:"condition/poisson_ruban_meteo.png", heure:"condition/poisson_ruban_heure.png"},
    {name:"Pesce dagli occhi rossi", bg:"condition/poisson_a_yeux_rouges_lieu.png", cond:"condition/poisson_a_yeux_rouges_meteo.png", heure:"condition/poisson_a_yeux_rouges_heure.png"},
    {name:"Re di aringhe", bg:"condition/regalec_lieu.png", cond:"condition/regalec_meteo.png", heure:"condition/regalec_heure.png"},
    {name:"Triglia di scoglio", bg:"condition/rouget_barbet_lieu.png", cond:"condition/rouget_barbet_meteo.png", heure:"condition/rouget_barbet_heure.png"},
    {name:"Gattuccio", bg:"condition/roussette_lieu.png", cond:"condition/roussette_meteo.png", heure:"condition/roussette_heure.png"},
    {name:"Lucioperca bianco", bg:"condition/sandre_blanc_lieu.png", cond:"condition/sandre_blanc_meteo.png", heure:"condition/sandre_blanc_heure.png"},
    {name:"Salmone atlantico", bg:"condition/saumon_atlantique_lieu.png", cond:"condition/saumon_atlantique_meteo.png", heure:"condition/saumon_atlantique_heure.png"},
    {name:"Salmone keta", bg:"condition/saumon_keta_lieu.png", cond:"condition/saumon_keta_meteo.png", heure:"condition/saumon_keta_heure.png"},
    {name:"Surombo", bg:"condition/saurel_lieu.png", cond:"condition/saurel_meteo.png", heure:"condition/saurel_heure.png"},
    {name:"Sardina", bg:"condition/sardine_lieu.png", cond:"condition/sardine_meteo.png", heure:"condition/sardine_heure.png"},
    {name:"Seppia europea", bg:"condition/seiche_europeenne_lieu.png", cond:"condition/seiche_europeenne_meteo.png", heure:"condition/seiche_europeenne_heure.png"},
    {name:"Siluro europeo", bg:"condition/silure_europeen_lieu.png", cond:"condition/silure_europeen_meteo.png", heure:"condition/silure_europeen_heure.png"},
    {name:"Tinca dorata", bg:"condition/tanche_doree_lieu.png", cond:"condition/tanche_doree_meteo.png", heure:"condition/tanche_doree_heure.png"},
    {name:"Girino", bg:"condition/tetard_lieu.png", cond:"condition/tetard_meteo.png", heure:"condition/tetard_heure.png"},
    {name:"Tilapia", bg:"condition/tilapia_lieu.png", cond:"condition/tilapia_meteo.png", heure:"condition/tilapia_heure.png"},
    {name:"Rombo chiodato", bg:"condition/turbot_lieu.png", cond:"condition/turbot_meteo.png", heure:"condition/turbot_heure.png"},
    {name:"Sanguinerola", bg:"condition/vairon_lieu.png", cond:"condition/vairon_meteo.png", heure:"condition/vairon_heure.png"},
    {name:"Zingel streber", bg:"condition/zingel_streber_lieu.png", cond:"condition/zingel_streber_meteo.png", heure:"condition/zingel_streber_heure.png"}
];

// 9. INSETTI
const bugList = [
    {name:"Actias neidhoederi", bg:"condition/actias_neidhoederi_lieu.png", cond:"condition/actias_neidhoederi_meteo.png", heure:"condition/actias_neidhoederi_heure.png"},
    {name:"Celastrina argiolus", bg:"condition/azure_de_porcelaine_lieu.png", cond:"condition/azure_de_porcelaine_meteo.png", heure:"condition/azure_de_porcelaine_heure.png"},
    {name:"Bombo", bg:"condition/bourdon_lieu.png", cond:"condition/bourdon_meteo.png", heure:"condition/bourdon_heure.png"},
    {name:"Cetonia stella blu", bg:"condition/cetoine_etoilee_bleue_lieu.png", cond:"condition/cetoine_etoilee_bleue_meteo.png", heure:"condition/cetoine_etoilee_bleue_heure.png"},
    {name:"Cicindela verde", bg:"condition/cicindele_verte_lieu.png", cond:"condition/cicindele_verte_meteo.png", heure:"condition/cicindele_verte_heure.png"},
    {name:"Cedronella", bg:"condition/citron_aspasia_lieu.png", cond:"condition/citron_aspasia_meteo.png", heure:"condition/citron_aspasia_heure.png"},
    {name:"Coccinella a 7 punti", bg:"condition/coccinelle_a_sept_points_lieu.png", cond:"condition/coccinelle_a_sept_points_meteo.png", heure:"condition/coccinelle_a_sept_points_heure.png"},
    {name:"Coccinella asiatica", bg:"condition/coccinelle_asiatique_lieu.png", cond:"condition/coccinelle_asiatique_meteo.png", heure:"condition/coccinelle_asiatique_heure.png"},
    {name:"Criocera dell'asparago", bg:"condition/criocere_de_lasperge_lieu.png", cond:"condition/criocere_de_lasperge_meteo.png", heure:"condition/criocere_de_lasperge_heure.png"},
    {name:"Cavalletta zampe massicce", bg:"condition/criquet_aux_pattes_massives_lieu.png", cond:"condition/criquet_aux_pattes_massives_meteo.png", heure:"condition/criquet_aux_pattes_massives_heure.png"},
    {name:"Agrion virgo", bg:"condition/grand_agrion_lieu.png", cond:"condition/grand_agrion_meteo.png", heure:"condition/grand_agrion_heure.png"},
    {name:"Libellula maculata", bg:"condition/libellule_tachetee_lieu.png", cond:"condition/libellule_tachetee_meteo.png", heure:"condition/libellule_tachetee_heure.png"},
    {name:"Farfalla anelli rossi", bg:"condition/papillon_a_anneaux_rouges_lieu.png", cond:"condition/papillon_a_anneaux_rouges_meteo.png", heure:"condition/papillon_a_anneaux_rouges_heure.png"},
    {name:"Farfalla collo rosso", bg:"condition/papillon_a_col_rouge_lieu.png", cond:"condition/papillon_a_col_rouge_meteo.png", heure:"condition/papillon_a_col_rouge_heure.png"},
    {name:"Farfalla bianca", bg:"condition/papillon_blanc_lieu.png", cond:"condition/papillon_blanc_meteo.png", heure:"condition/papillon_blanc_heure.png"},
    {name:"Farfalla dorata", bg:"condition/papillon_dore_lieu.png", cond:"condition/papillon_dore_meteo.png", heure:"condition/papillon_dore_heure.png"},
    {name:"Parnassius", bg:"condition/parnassien_lieu.png", cond:"condition/parnassien_meteo.png", heure:"condition/parnassien_heure.png"},
    {name:"Pieride del crescione", bg:"condition/pieride_du_cresson_lieu.png", cond:"condition/pieride_du_cresson_meteo.png", heure:"condition/pieride_du_cresson_heure.png"},
    {name:"Cimice Picasso", bg:"condition/punaise_picasso_lieu.png", cond:"condition/punaise_picasso_meteo.png", heure:"condition/punaise_picasso_heure.png"},
    {name:"Pirocroa", bg:"condition/pyrochroa_lieu.png", cond:"condition/pyrochroa_meteo.png", heure:"condition/pyrochroa_heure.png"},
    {name:"Cimice rossonera", bg:"condition/pyrrhocoris_apterus_lieu.png", cond:"condition/pyrrhocoris_apterus_meteo.png", heure:"condition/pyrrhocoris_apterus_heure.png"},
    {name:"Cavalletta dell'oasi", bg:"condition/sauterelle_de_loasis_lieu.png", cond:"condition/sauterelle_de_loasis_meteo.png", heure:"condition/sauterelle_de_loasis_heure.png"},
    {name:"Scarabeo unicorno", bg:"condition/scarabee_unicorne_lieu.png", cond:"condition/scarabee_unicorne_meteo.png", heure:"condition/scarabee_unicorne_heure.png"}
];

// 10. UCCELLI
const birdList = [
    {name:"Ara gialloblu", bg:"condition/ara_bleu_et_jaune_lieu.png", cond:"condition/ara_bleu_et_jaune_meteo.png", heure:"condition/ara_bleu_et_jaune_heure.png"},
    {name:"Ara ali verdi", bg:"condition/ara_rouge_et_vert_lieu.png", cond:"condition/ara_rouge_et_vert_meteo.png", heure:"condition/ara_rouge_et_vert_heure.png"},
    {name:"Ara indaco", bg:"condition/ara_indigo_lieu.png", cond:"condition/ara_indigo_meteo.png", heure:"condition/ara_indigo_heure.png"},
    {name:"Ballerina bianca", bg:"condition/bergeronnette_grise_lieu.png", cond:"condition/bergeronnette_grise_meteo.png", heure:"condition/bergeronnette_grise_heure.png"},
    {name:"Ciuffolotto", bg:"condition/bouvreuil_lieu.png", cond:"condition/bouvreuil_meteo.png", heure:"condition/bouvreuil_heure.png"},
    {name:"Ciuffolotto ventre rosso", bg:"condition/bouvreuil_a_ventre_rouge_lieu.png", cond:"condition/bouvreuil_a_ventre_rouge_meteo.png", heure:"condition/bouvreuil_a_ventre_rouge_heure.png"},
    {name:"Tangara del paradiso", bg:"condition/calliste_septicolore_lieu.png", cond:"condition/calliste_septicolore_meteo.png", heure:"condition/calliste_septicolore_heure.png"},
    {name:"Gobbo rugginoso", bg:"condition/canard_a_tete_blanche_lieu.png", cond:"condition/canard_a_tete_blanche_meteo.png", heure:"condition/canard_a_tete_blanche_heure.png"},
    {name:"Germano reale", bg:"condition/canard_colvert_lieu.png", cond:"condition/canard_colvert_meteo.png", heure:"condition/canard_colvert_heure.png"},
    {name:"Fischione", bg:"condition/canard_siffleur_lieu.png", cond:"condition/canard_siffleur_meteo.png", heure:"condition/canard_siffleur_heure.png"},
    {name:"Cardinale corona grigia", bg:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_lieu.png", cond:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_meteo.png", heure:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_heure.png"},
    {name:"Colomba jambu", bg:"condition/colombe_jambu_lieu.png", cond:"condition/colombe_jambu_meteo.png", heure:"condition/colombe_jambu_heure.png"},
    {name:"Diamante mandarino", bg:"condition/diamant_mandarin_lieu.png", cond:"condition/diamant_mandarin_meteo.png", heure:"condition/diamant_mandarin_heure.png"},
    {name:"Re degli edredoni", bg:"condition/eider_royal_lieu.png", cond:"condition/eider_royal_meteo.png", heure:"condition/eider_royal_heure.png"},
    {name:"Fagiano venerato", bg:"condition/faisan_a_ventre_blanc_lieu.png", cond:"condition/faisan_a_ventre_blanc_meteo.png", heure:"condition/faisan_a_ventre_blanc_heure.png"},
    {name:"Falco cuculo", bg:"condition/faucon_a_pattes_rouges_lieu.png", cond:"condition/faucon_a_pattes_rouges_meteo.png", heure:"condition/faucon_a_pattes_rouges_heure.png"},
    {name:"Falco pellegrino", bg:"condition/faucon_pelerin_lieu.png", cond:"condition/faucon_pelerin_meteo.png", heure:"condition/faucon_pelerin_heure.png"},
    {name:"Falco rosso", bg:"condition/faucon_rouge_lieu.png", cond:"condition/faucon_rouge_meteo.png", heure:"condition/faucon_rouge_heure.png"},
    {name:"Fenicottero americano", bg:"condition/flamant_rose_americain_lieu.png", cond:"condition/flamant_rose_americain_meteo.png", heure:"condition/flamant_rose_americain_heure.png"},
    {name:"Fringuello", bg:"condition/fringilla_coelebs_lieu.png", cond:"condition/fringilla_coelebs_meteo.png", heure:"condition/fringilla_coelebs_heure.png"},
    {name:"Pigliamosche verditer", bg:"condition/gobemouche_vertdegris_lieu.png", cond:"condition/gobemouche_vertdegris_meteo.png", heure:"condition/gobemouche_vertdegris_heure.png"},
    {name:"Gabbiano", bg:"condition/goeland_lieu.png", cond:"condition/goeland_meteo.png", heure:"condition/goeland_heure.png"},
    {name:"Rigogolo", bg:"condition/golden_oriole_lieu.png", cond:"condition/golden_oriole_meteo.png", heure:"condition/golden_oriole_heure.png"},
    {name:"Gufo reale", bg:"condition/grand_duc_deurope_lieu.png", cond:"condition/grand_duc_deurope_meteo.png", heure:"condition/grand_duc_deurope_heure.png"},
    {name:"Fenicottero rosa", bg:"condition/grand_flamant_lieu.png", cond:"condition/grand_flamant_meteo.png", heure:"condition/grand_flamant_heure.png"},
    {name:"Picchio pileato", bg:"condition/grand_pic_lieu.png", cond:"condition/grand_pic_meteo.png", heure:"condition/grand_pic_heure.png"},
    {name:"Frosone", bg:"condition/grosbec_lieu.png", cond:"condition/grosbec_meteo.png", heure:"condition/grosbec_heure.png"},
    {name:"Gruccione", bg:"condition/guepier_deurope_lieu.png", cond:"condition/guepier_deurope_meteo.png", heure:"condition/guepier_deurope_heure.png"},
    {name:"Pesciaiola", bg:"condition/harle_piette_lieu.png", cond:"condition/harle_piette_meteo.png", heure:"condition/harle_piette_heure.png"},
    {name:"Gufo comune", bg:"condition/hibou_moyen_duc_lieu.png", cond:"condition/hibou_moyen_duc_meteo.png", heure:"condition/hibou_moyen_duc_heure.png"},
    {name:"Uccello giardiniere", bg:"condition/jardinier_a_tete_jaune_lieu.png", cond:"condition/jardinier_a_tete_jaune_meteo.png", heure:"condition/jardinier_a_tete_jaune_heure.png"},
    {name:"Fanello nordico", bg:"condition/linotte_a_dos_blanc_lieu.png", cond:"condition/linotte_a_dos_blanc_meteo.png", heure:"condition/linotte_a_dos_blanc_heure.png"},
    {name:"Uccello azzurro orientale", bg:"condition/merle_bleu_de_lest_lieu.png", cond:"condition/merle_bleu_de_lest_meteo.png", heure:"condition/merle_bleu_de_lest_heure.png"},
    {name:"Cincia dal mento d'argento", bg:"condition/mesange_a_menton_argent_lieu.png", cond:"condition/mesange_a_menton_argent_meteo.png", heure:"condition/mesange_a_menton_argent_heure.png"},
    {name:"Cinciarella", bg:"condition/mesange_bleue_lieu.png", cond:"condition/mesange_bleue_meteo.png", heure:"condition/mesange_bleue_heure.png"},
    {name:"Pigliamosche ventre giallo", bg:"condition/moucherolle_a_ventre_jaune_lieu.png", cond:"condition/moucherolle_a_ventre_jaune_meteo.png", heure:"condition/moucherolle_a_ventre_jaune_heure.png"},
    {name:"Gabbiano comune", bg:"condition/mouette_lieu.png", cond:"condition/mouette_meteo.png", heure:"condition/mouette_heure.png"},
    {name:"Basettino", bg:"condition/panure_a_moustache_lieu.png", cond:"condition/panure_a_moustache_meteo.png", heure:"condition/panure_a_moustache_heure.png"},
    {name:"Pavone bianco", bg:"condition/paon_blanc_lieu.png", cond:"condition/paon_blanc_meteo.png", heure:"condition/paon_blanc_heure.png"},
    {name:"Pavone blu", bg:"condition/paon_bleu_lieu.png", cond:"condition/paon_bleu_meteo.png", heure:"condition/paon_bleu_heure.png"},
    {name:"Pavone nero", bg:"condition/paon_noir_lieu.png", cond:"condition/paon_noir_meteo.png", heure:"condition/paon_noir_heure.png"},
    {name:"Pavone verde", bg:"condition/paon_vert_lieu.png", cond:"condition/paon_vert_meteo.png", heure:"condition/paon_vert_heure.png"},
    {name:"Fenicottero minore", bg:"condition/petit_flamant_lieu.png", cond:"condition/petit_flamant_meteo.png", heure:"condition/petit_flamant_heure.png"},
    {name:"Averla capirossa", bg:"condition/piegrieche_a_tete_rousse_lieu.png", cond:"condition/piegrieche_a_tete_rousse_meteo.png", heure:"condition/piegrieche_a_tete_rousse_heure.png"},
    {name:"Colomba frugivora", bg:"condition/pigeon_aux_fruits_dor_lieu.png", cond:"condition/pigeon_aux_fruits_dor_meteo.png", heure:"condition/pigeon_aux_fruits_dor_heure.png"},
    {name:"Colomba occhi gialli", bg:"condition/pigeon_aux_yeux_jaunes_lieu.png", cond:"condition/pigeon_aux_yeux_jaunes_meteo.png", heure:"condition/pigeon_aux_yeux_jaunes_heure.png"},
    {name:"Colombella", bg:"condition/pigeon_colombin_lieu.png", cond:"condition/pigeon_colombin_meteo.png", heure:"condition/pigeon_colombin_heure.png"},
    {name:"Piccione Wonga", bg:"condition/pigeon_de_wonga_lieu.png", cond:"condition/pigeon_de_wonga_meteo.png", heure:"condition/pigeon_de_wonga_heure.png"},
    {name:"Piccione rosa", bg:"condition/pigeon_rose_lieu.png", cond:"condition/pigeon_rose_meteo.png", heure:"condition/pigeon_rose_heure.png"},
    {name:"Fringuello", bg:"condition/pinson_lieu.png", cond:"condition/pinson_meteo.png", heure:"condition/pinson_heure.png"},
    {name:"Pettirosso", bg:"condition/rougegorge_lieu.png", cond:"condition/rougegorge_meteo.png", heure:"condition/rougegorge_heure.png"},
    {name:"Picchio muratore", bg:"condition/sittelle_lieu.png", cond:"condition/sittelle_meteo.png", heure:"condition/sittelle_heure.png"},
    {name:"Sterna", bg:"condition/sterne_lieu.png", cond:"condition/sterne_meteo.png", heure:"condition/sterne_heure.png"},
    {name:"Sterna bianca", bg:"condition/sterne_blanche_lieu.png", cond:"condition/sterne_blanche_meteo.png", heure:"condition/sterne_blanche_heure.png"},
    {name:"Casarca", bg:"condition/tadorne_casarca_lieu.png", cond:"condition/tadorne_casarca_meteo.png", heure:"condition/tadorne_casarca_heure.png"},
    {name:"Tortora testa grigia", bg:"condition/tourterelle_a_tete_grise_lieu.png", cond:"condition/tourterelle_a_tete_grise_meteo.png", heure:"condition/tourterelle_a_tete_grise_heure.png"},
    {name:"Tortora dal collare", bg:"condition/tourterelle_grise_lieu.png", cond:"condition/tourterelle_grise_meteo.png", heure:"condition/tourterelle_grise_heure.png"},
    {name:"Tortora tigrata", bg:"condition/tourterelle_tigrine_lieu.png", cond:"condition/tourterelle_tigrine_meteo.png", heure:"condition/tourterelle_tigrine_heure.png"},
    {name:"Scricciolo", bg:"condition/troglodyte_lieu.png", cond:"condition/troglodyte_meteo.png", heure:"condition/troglodyte_heure.png"}
];

// 11. QUIZ (Rinominato QUIZ_DATA per coerenza con app.js)
const QUIZ_DATA = [
    { q: "Chi è la guida del villaggio?", o: ["Albert Jr.", "Barnabé", "Eric"], a: 0 },
    { q: "Dove si trova l'Acantharchus pomotis?", o: ["Mare Calmo", "Lago della Foresta", "Fiume Aurora"], a: 0 },
    { q: "Quale NPC gestisce i ritrovamenti?", o: ["Il Collezionista", "Bob", "Massimo"], a: 0 },
    { q: "Quale meteo crea l'arcobaleno?", o: ["Temporale", "Nebbia", "Sole dopo pioggia"], a: 2 },
    { q: "Dov'è il Villaggio Pescatori?", o: ["Nord-Est", "Sud-Ovest", "Est"], a: 1 },
    { q: "L'Actias neidhoederi è:", o: ["Mattiniero", "Diurno", "Notturno"], a: 2 },
    { q: "Dove vive il Capibara?", o: ["Le Rovine", "Il Trampolino", "La Spiaggia"], a: 0 },
    { q: "Chi vende gli animali (cani)?", o: ["Vernie", "Joan", "Andrew"], a: 1 },
    { q: "Dove pescare il Re di aringhe?", o: ["Fiumi", "Laghi", "Oceano"], a: 2 },
    { q: "Dov'è la zona termale?", o: ["A Nord", "A Sud", "A Ovest"], a: 0 },
    { q: "Lo Scarabeo unicorno vive:", o: ["Molo Orientale", "Campi", "Foresta"], a: 0 },
    { q: "L'Ara indaco è un:", o: ["Pesce", "Insetto", "Uccello"], a: 2 },
    { q: "La Carpa Farfalla vive in:", o: ["Acqua dolce", "Acqua salata", "Lago Prateria"], a: 2 },
    { q: "Dove si trova l'NPC Will?", o: ["Vicino al mare", "In montagna", "Nella foresta"], a: 0 },
    { q: "Colore del pulsante PESCI?", o: ["Verde", "Blu", "Arancione"], a: 1 },
    { q: "Il Bombo vive in:", o: ["Laghi", "Campi di fiori", "Grotte"], a: 1 },
    { q: "La Lontra si trova:", o: ["Faro", "Villaggio Pescatori", "Rovine"], a: 1 },
    { q: "Il Panda vive vicino a:", o: ["Trampolino", "Villaggio", "Molo"], a: 0 },
    { q: "Lo Sperlano vive in:", o: ["Lago Prateria", "Lago Alto", "Oceano"], a: 0 },
    { q: "Annie si trova:", o: ["Piazza Centrale", "Spiaggia", "Foresta"], a: 0 },
    { q: "Il Lama vive in:", o: ["Spiaggia Viola", "Montagna", "Fiume"], a: 0 },
    { q: "Voto su 20 per la mappa?", o: ["5", "0", "20"], a: 2 },
    { q: "Il Gambero blu vive in:", o: ["Lago Foresta", "Oceano", "Mare Calmo"], a: 0 },
    { q: "La Montagna della Balena è a:", o: ["Sud", "Nord", "Ovest"], a: 2 },
    { q: "Maptopia serve a:", o: ["Vendere oggetti", "Localizzare risorse", "Sostituire il gioco"], a: 1 },
    { q: "La Ballerina bianca è un:", o: ["Uccello", "Pesce", "Abitante"], a: 1 },
    { q: "Il Cervo vive in:", o: ["Spiaggia", "Foresta di Querce", "Città"], a: 1 },
    { q: "La Cedronella è un:", o: ["Frutto", "Insetto", "Pesce"], a: 1 },
    { q: "Il Molo Orientale è a:", o: ["Nord", "Est", "Sud"], a: 1 },
    { q: "Bob è un:", o: ["Animale", "NPC", "Luogo"], a: 1 }
];