// --- ENGLISH DATA (data-en.js) ---

// 1. UI TEXTS
const TEXTS = {
    title: "MAPTOPIA EN",
    enterBtn: "✨ ENTER MAP ✨",
    menu: {
        pnj: "NPCs",
        animals: "ANIMALS",
        bus: "BUS",
        shops: "SHOPS",
        places: "LOCATIONS",
        fish: "FISH",
        bugs: "BUGS",
        birds: "BIRDS",
        resources: "RESOURCES"
    },
    chat: {
        success: "✅ Message sent successfully!",
        error: "❌ Error sending message.",
        incomplete: "⚠️ Please fill in all fields.",
        wait: "Sending..."
    },
    quiz: {
        success: "✅ CORRECT!",
        error: "❌ WRONG!",
        finishTitle: "🏆 EXPERT CONFIRMED!",
        finishText: "You know Heartopia like the back of your hand.",
        quitBtn: "QUIT QUIZ"
    },
    like: {
        thankyou: "THANK YOU!",
        already: "You have already voted!"
    }
};

// 2. NPC LIST
const PNJ_DATA = [
    [-471, 501, "Bob", "pnj/bob.png"],
    [-526, 499, "Atara", "pnj/atara.png"],
    [-478, 493, "Collector", "pnj/collectioneur.png"],
    [-469, 488, "Dorothy", "pnj/dorothée.png"],
    [-446, 493, "Massimo", "pnj/massimo.png"],
    [-412, 418, "Ka Ching", "pnj/ka ching.png"],
    [-399, 591, "Andrew", "pnj/andrew.png"],
    [-259, 522, "Eric", "pnj/eric.png"],
    [-456, 549, "Vanya", "pnj/vanya.png"],
    [-502, 582, "Naniwa", "pnj/naniwa.png"],
    [-502, 519, "Mrs. Joan", "pnj/mme joan.png"],
    [-807, 419, "Will", "pnj/will.png"],
    [-355, 809, "Patti", "pnj/patti.png"],
    [-653, 225, "Vernie", "pnj/vernie.png"],
    [-498, 526, "Bailey j", "pnj/bayleyj.png"],
    [-528.3, 560.3, "Blanc", "pnj/blanc.png"],
    [-499.8, 499.0, "Annie", "pnj/annie.png"],
    [-532.4, 634.8, "Albert Jr.", "pnj/albert jr.png"],
    [-734.8, 445.8, "Bill", "pnj/bill.png"]
];

// 3. BUS STOPS
const BUS_DATA = [
    ["West Suburbs",[-533,340]], ["Village Suburbs",[-519,639]], ["Fishing Village",[-654,479]], 
    ["Flower Field",[-532,218]], ["Thermal Mountain",[-222,512]], ["North Suburbs",[-373,480]], 
    ["Central Plaza",[-497,481]], ["Forest",[-500,798]]
];

// 4. SHOPS
const SHOP_DATA = [
    [-472,487,"Clothes","vetement.png"],[-474,503,"Furniture","Meuble.png"],
    [-496.4,520.6,"Pet Shop","chien.png"],[-440,467,"Bookstore","Librairie.png"]
];

// 5. ANIMALS
const ANIMAL_DATA = [
    {pos: [-691, 783], name: "Panda", img: "panda.png", radius: 60},
    {pos: [-184, 291], name: "Capybara", img: "capybara.png", radius: 50},
    {pos: [-533, 340], name: "Rabbit", img: "lapin.png", radius: 40},
    {pos: [-649, 185], name: "Fox", img: "renard.png", radius: 70},
    {pos: [-737, 512], name: "Otter", img: "loutre.png", radius: 40},
    {pos: [-354.3, 277.3], name: "Mink", img: "vison.png", radius: 10},
    {pos: [-531, 805], name: "Deer", img: "cerf.png", radius: 60},
    {pos: [-725, 208], name: "Llama", img: "lama.png", radius: 50}
];

// 6. LOCATIONS
const LIEUX_DATA = [
    {pos:[-538,492], name:"Central Plaza", type:"label-ville", startOn:true}, 
    {pos:[-692,506], name:"Fishing Village", type:"label-ville", startOn:true}, 
    {pos:[-438,513], name:"Residents Street", type:"label-ville", startOn:true}, 
    {pos:[-649,185], name:"Flower Field", type:"label-ville", startOn:true}, 
    {pos:[-440,184], name:"Whale Mountain", type:"label-ville", startOn:true}, 
    {pos:[-184,291], name:"The Ruins", type:"label-ville", startOn:true}, 
    {pos:[-223,501], name:"Thermal Mountain", type:"label-ville", startOn:true}, 
    {pos:[-228,627], name:"Rocky Cliff", type:"label-ville", startOn:true}, 
    {pos:[-531,805], name:"Oak Forest", type:"label-ville", startOn:true}, 
    {pos:[-494,429], name:"Arts Street", type:"label-ville", startOn:true}, 
    {pos:[-510,558], name:"Garden Street", type:"label-ville", startOn:true}, 
    {pos:[-736,602], name:"Oriental Dock", type:"label-ville", startOn:true}, 
    {pos:[-690,402], name:"The Dock", type:"label-ville", startOn:true}, 
    {pos:[-780,387], name:"Lighthouse", type:"label-ville", startOn:true}, 
    {pos:[-691,783], name:"Diving Board", type:"label-ville", startOn:true}, 
    {pos:[-338,933], name:"Forest Island", type:"label-ville", startOn:true}, 
    {pos:[-587,406], name:"Suburbs", type:"label-ville", startOn:true}, 
    {pos:[-725,208], name:"Purple Beach", type:"label-ville", startOn:true}, 
    {pos:[-783,478], name:"Calm Sea", type:"label-eau", startOn:true}, 
    {pos:[-534,92], name:"Whale Sea", type:"label-eau", startOn:true}, 
    {pos:[-68,497], name:"Ancient Sea", type:"label-eau", startOn:true}, 
    {pos:[-536,232], name:"Meadow Lake", type:"label-eau", startOn:true}, 
    {pos:[-337,319], name:"Aurora River", type:"label-eau", startOn:true}, 
    {pos:[-176,394], name:"Volcanic Lake", type:"label-eau", startOn:true}, 
    {pos:[-265,537], name:"Hot Spring Lake", type:"label-eau", startOn:true}, 
    {pos:[-344,652], name:"Shallow River", type:"label-eau", startOn:true}, 
    {pos:[-598,748], name:"Forest Lake", type:"label-eau", startOn:true}, 
    {pos:[-431,774], name:"Upper Forest Lake", type:"label-eau", startOn:true}, 
    {pos:[-608,481], name:"Suburban Lake", type:"label-eau", startOn:true}, 
    {pos:[-669,368], name:"Quiet River", type:"label-eau", startOn:true}, 
    {pos:[-674,627], name:"Giant Tree River", type:"label-eau", startOn:true}, 
    {pos:[-600,600], name:"Mill Flower Field", type:"label-ville", startOn:true}, 
    {pos:[-670,450], name:"East Pontoon", type:"label-ville", startOn:true}
];

// 7. RESOURCES
const resourcesData = {
    "Raspberry": { icon: "resource/framboise.png", positions: [[-680.8, 330.9], [-668.5, 352.1], [-667.9, 268.5], [-648.3, 288.6], [-613.5, 317.4], [-602.8, 274.5], [-617.6, 211.6], [-571.5, 254.4], [-538.9, 208.6], [-527.8, 251.6], [-535.8, 288.3], [-503.1, 242.9], [-495, 222.4], [-453.8, 222.4], [-438.6, 246], [-395, 247.4], [-387.1, 269.5]] },
    "Blueberry": { icon: "resource/myrtille.png", positions: [[-642.9, 371.9], [-631.9, 368.4], [-628.5, 365.5], [-606.8, 350.3], [-602.5, 342.3], [-590.1, 334.1], [-575.6, 332.1], [-562.1, 330], [-544.9, 324.5], [-518.4, 320.3], [-515.9, 320.5], [-500.8, 321.1], [-479.3, 328.6], [-468.3, 320], [-437.3, 313.9], [-411.4, 311.4], [-400.3, 311.4], [-379.5, 304.1], [-327.4, 352], [-313.6, 339], [-328.6, 371.5], [-324.4, 389.3], [-297.9, 410.8], [-271.6, 395.4], [-319.9, 413.5], [-330.4, 421.6], [-333.4, 450], [-338.6, 468.6], [-297.4, 484.4], [-349, 489.4], [-356.5, 499.3], [-360.4, 526.4], [-355.5, 545.1], [-352.9, 565.9], [-316, 558.1], [-363.6, 578.4], [-365.3, 609], [-360.9, 628.1], [-343, 634], [-388, 655.4], [-400.9, 654.3], [-421.9, 656.4], [-444.1, 670.6], [-462.5, 654], [-476.8, 654.6], [-491.6, 656.3], [-506.4, 672.4], [-525.4, 688], [-542.6, 650], [-559.3, 644.9], [-575.6, 651], [-597.8, 643.8], [-604.8, 633.8], [-627.9, 619.4]] },
    "Apple": { icon: "resource/pomme.png", positions: [[-356.3, 493], [-365.4, 560.1], [-362.4, 581], [-324.6, 570.1], [-296, 610.3], [-365.6, 619.5], [-362.8, 628.5], [-393.5, 654.8], [-420.6, 653.3], [-436.1, 665.4], [-444.4, 685.1], [-436.6, 697.5], [-458.4, 744.9], [-505, 677.3], [-494.5, 657], [-459.8, 653.6], [-530.1, 677.9], [-540.1, 648.6], [-592.8, 676.6], [-606.9, 634.1], [-629.3, 623]] },
    "Grand Tree": { icon: "resource/grand arbre.png", positions: [[-612, 424.5], [-641.8, 369], [-351, 329.5], [-414.3, 337.1], [-396.3, 608.9], [-376.3, 624], [-616, 593.6], [-672.3, 642]] },
    "Slippery Oak Wood": { icon: "resource/bois de chaine glissant.png", positions: [[-532, 787.3]] },
    "Stone": { icon: "resource/pierre.png", positions: [[-615.9, 316], [-641.5, 278.8], [-558.4, 257.4], [-535, 292], [-499.5, 241.1], [-466.8, 283.1], [-407.1, 244.1], [-284, 402.8], [-254.6, 367.9], [-309.4, 479.1], [-263, 466.6], [-289.1, 544.6], [-315.5, 567.9], [-298.6, 625.4], [-391.3, 726.9], [-443.6, 697], [-468.6, 733.8], [-519, 714.9], [-564.9, 732.8], [-605.1, 680.3], [-673.9, 684.1]] },
    "Fluorite": { icon: "resource/fluorite.png", positions: [[-417.8, 313.8]] },
    "Orange": { icon: "resource/orange.png", positions: [[-650.1, 370.9], [-639.5, 372], [-607.3, 351.4], [-602.9, 343.5], [-588.6, 336.6], [-559.6, 329.5], [-542.1, 324.8], [-515, 319.5], [-470.5, 321], [-461.4, 271.5], [-410.8, 314], [-397.3, 310.1], [-310.9, 339.3], [-327.6, 373.9], [-324.9, 391.9], [-295.4, 411.1], [-330.4, 420.9], [-333.8, 452.9]] }
};

// 8. FISH (Translated Common Names)
const fishList = [
    {name:"Bleak", bg:"condition/ablette_lieu.png", cond:"condition/ablette_meteo.png", heure:"condition/ablette_heure.png"},
    {name:"Acantharchus pomotis", bg:"condition/acantharchus_pomotis_lieu.png", cond:"condition/acantharchus_pomotis_meteo.png", heure:"condition/acantharchus_pomotis_heure.png"},
    {name:"European Eel", bg:"condition/anguille_europeenne_lieu.png", cond:"condition/anguille_europeenne_meteo.png", heure:"condition/anguille_europeenne_heure.png"},
    {name:"Aphyosemion striatum", bg:"condition/aphyosemion_striatum_lieu.png", cond:"condition/aphyosemion_striatum_meteo.png", heure:"condition/aphyosemion_striatum_heure.png"},
    {name:"Barbel", bg:"condition/barbeau_lieu.png", cond:"condition/barbeau_meteo.png", heure:"condition/barbeau_heure.png"},
    {name:"Small Barbel", bg:"condition/barbillon_lieu.png", cond:"condition/barbillon_meteo.png", heure:"condition/barbillon_heure.png"},
    {name:"Anglerfish", bg:"condition/baudroie_lieu.png", cond:"condition/baudroie_meteo.png", heure:"condition/baudroie_heure.png"},
    {name:"Hermit Crab", bg:"condition/bernard_lhermite_lieu.png", cond:"condition/bernard_lhermite_meteo.png", heure:"condition/bernard_lhermite_heure.png"},
    {name:"River Blenny", bg:"condition/blennie_de_riviere_lieu.png", cond:"condition/blennie_de_riviere_meteo.png", heure:"condition/blennie_de_riviere_heure.png"},
    {name:"Bonito", bg:"condition/bonite_lieu.png", cond:"condition/bonite_meteo.png", heure:"condition/bonite_heure.png"},
    {name:"Spotted Pike", bg:"condition/brochet_tachete_lieu.png", cond:"condition/brochet_tachete_meteo.png", heure:"condition/brochet_tachete_heure.png"},
    {name:"Silver Carp", bg:"condition/carpe_argente_lieu.png", cond:"condition/carpe_argente_meteo.png", heure:"condition/carpe_argente_heure.png"},
    {name:"European Carp", bg:"condition/carpe_europeenne_lieu.png", cond:"condition/carpe_europeenne_meteo.png", heure:"condition/carpe_europeenne_heure.png"},
    {name:"Butterfly Carp", bg:"condition/carpe_papillon_lieu.png", cond:"condition/carpe_papillon_meteo.png", heure:"condition/carpe_papillon_heure.png"},
    {name:"Black Carp", bg:"condition/carpe_noire_lieu.png", cond:"condition/carpe_noire_meteo.png", heure:"condition/carpe_noire_heure.png"},
    {name:"Sculpin", bg:"condition/chabot_lieu.png", cond:"condition/chabot_meteo.png", heure:"condition/chabot_heure.png"},
    {name:"Silver Chimaera", bg:"condition/chimere_argentee_lieu.png", cond:"condition/chimere_argentee_meteo.png", heure:"condition/chimere_argentee_heure.png"},
    {name:"Comet Goldfish", bg:"condition/comete_coussut_lieu.png", cond:"condition/comete_coussut_meteo.png", heure:"condition/comete_coussut_heure.png"},
    {name:"Stream Crab", bg:"condition/crabe_de_ruisseau_lieu.png", cond:"condition/crabe_de_ruisseau_meteo.png", heure:"condition/crabe_de_ruisseau_heure.png"},
    {name:"Sea Shrimp", bg:"condition/crevette_de_la_mer_lieu.png", cond:"condition/crevette_de_la_mer_meteo.png", heure:"condition/crevette_de_la_mer_heure.png"},
    {name:"Green Shrimp", bg:"condition/crevette_verte_lieu.png", cond:"condition/crevette_verte_meteo.png", heure:"condition/crevette_verte_heure.png"},
    {name:"Noble Crayfish", bg:"condition/ecrevisse_noble_lieu.png", cond:"condition/ecrevisse_noble_meteo.png", heure:"condition/ecrevisse_noble_heure.png"},
    {name:"Blue Noble Crayfish", bg:"condition/ecrevisse_noble_bleue_lieu.png", cond:"condition/ecrevisse_noble_bleue_meteo.png", heure:"condition/ecrevisse_noble_bleue_heure.png"},
    {name:"Haddock", bg:"condition/eglefin_lieu.png", cond:"condition/eglefin_meteo.png", heure:"condition/eglefin_heure.png"},
    {name:"Smelt", bg:"condition/eperlan_lieu.png", cond:"condition/eperlan_meteo.png", heure:"condition/eperlan_heure.png"},
    {name:"Whitefish", bg:"condition/fera_lieu.png", cond:"condition/fera_meteo.png", heure:"condition/fera_heure.png"},
    {name:"Large Black Bass", bg:"condition/grand_blackbasse_lieu.png", cond:"condition/grand_blackbasse_meteo.png", heure:"condition/grand_blackbasse_heure.png"},
    {name:"European Frog", bg:"condition/grenouille_europeenne_lieu.png", cond:"condition/grenouille_europeenne_meteo.png", heure:"condition/grenouille_europeenne_heure.png"},
    {name:"Goby", bg:"condition/gobie_lieu.png", cond:"condition/gobie_meteo.png", heure:"condition/gobie_heure.png"},
    {name:"Tub Gurnard", bg:"condition/grondin_perlon_lieu.png", cond:"condition/grondin_perlon_meteo.png", heure:"condition/grondin_perlon_heure.png"},
    {name:"Seahorse", bg:"condition/hippocampe_lieu.png", cond:"condition/hippocampe_meteo.png", heure:"condition/hippocampe_heure.png"},
    {name:"Huchen", bg:"condition/huchon_lieu.png", cond:"condition/huchon_meteo.png", heure:"condition/huchon_heure.png"},
    {name:"European Spiny Lobster", bg:"condition/langouste_europeenne_lieu.png", cond:"condition/langouste_europeenne_meteo.png", heure:"condition/langouste_europeenne_heure.png"},
    {name:"Flower Loach", bg:"condition/loche_des_fleurs_lieu.png", cond:"condition/loche_des_fleurs_meteo.png", heure:"condition/loche_des_fleurs_heure.png"},
    {name:"Stone Loach", bg:"condition/loche_des_rochers_lieu.png", cond:"condition/loche_des_rochers_meteo.png", heure:"condition/loche_des_rochers_heure.png"},
    {name:"Monkfish", bg:"condition/lotte_lieu.png", cond:"condition/lotte_meteo.png", heure:"condition/lotte_heure.png"},
    {name:"Atlantic Mackerel", bg:"condition/maquereau_atlantique_lieu.png", cond:"condition/maquereau_atlantique_meteo.png", heure:"condition/maquereau_atlantique_heure.png"},
    {name:"Mussel", bg:"condition/moule_lieu.png", cond:"condition/moule_meteo.png", heure:"condition/moule_heure.png"},
    {name:"Arctic Char", bg:"condition/omble_chevalier_lieu.png", cond:"condition/omble_chevalier_meteo.png", heure:"condition/omble_chevalier_heure.png"},
    {name:"Croaker", bg:"condition/ombrine_lieu.png", cond:"condition/ombrine_meteo.png", heure:"condition/ombrine_heure.png"},
    {name:"Blackspot Seabream", bg:"condition/pagellus_bogaraveo_lieu.png", cond:"condition/pagellus_bogaraveo_meteo.png", heure:"condition/pagellus_bogaraveo_heure.png"},
    {name:"Sea Perch", bg:"condition/perche_de_mer_lieu.png", cond:"condition/perche_de_mer_meteo.png", heure:"condition/perche_de_mer_heure.png"},
    {name:"Plum Perch", bg:"condition/perche_de_prunier_lieu.png", cond:"condition/perche_de_prunier_meteo.png", heure:"condition/perche_de_prunier_heure.png"},
    {name:"River Perch", bg:"condition/perche_de_riviere_lieu.png", cond:"condition/perche_de_riviere_meteo.png", heure:"condition/perche_de_riviere_heure.png"},
    {name:"Octopus", bg:"condition/pieuvre_lieu.png", cond:"condition/pieuvre_meteo.png", heure:"condition/pieuvre_heure.png"},
    {name:"Dwarf Octopus", bg:"condition/pieuvre_naine_atlantique_lieu.png", cond:"condition/pieuvre_naine_atlantique_meteo.png", heure:"condition/pieuvre_naine_atlantique_heure.png"},
    {name:"Tigerfish", bg:"condition/poissontigre_a_ventre_rouge_lieu.png", cond:"condition/poissontigre_a_ventre_rouge_meteo.png", heure:"condition/poissontigre_a_ventre_rouge_heure.png"},
    {name:"European Plaice", bg:"condition/plie_europeenne_lieu.png", cond:"condition/plie_europeenne_meteo.png", heure:"condition/plie_europeenne_heure.png"},
    {name:"Clownfish", bg:"condition/poissonclown_lieu.png", cond:"condition/poissonclown_meteo.png", heure:"condition/poissonclown_heure.png"},
    {name:"Stickleback", bg:"condition/poisson_epineux_lieu.png", cond:"condition/poisson_epineux_meteo.png", heure:"condition/poisson_epineux_heure.png"},
    {name:"River Pufferfish", bg:"condition/poissonglobe_de_riviere_lieu.png", cond:"condition/poissonglobe_de_riviere_meteo.png", heure:"condition/poissonglobe_de_riviere_heure.png"},
    {name:"Goldfish", bg:"condition/poisson_rouge_lieu.png", cond:"condition/poisson_rouge_meteo.png", heure:"condition/poisson_rouge_heure.png"},
    {name:"Ribbonfish", bg:"condition/poisson_ruban_lieu.png", cond:"condition/poisson_ruban_meteo.png", heure:"condition/poisson_ruban_heure.png"},
    {name:"Red-Eyed Fish", bg:"condition/poisson_a_yeux_rouges_lieu.png", cond:"condition/poisson_a_yeux_rouges_meteo.png", heure:"condition/poisson_a_yeux_rouges_heure.png"},
    {name:"Oarfish", bg:"condition/regalec_lieu.png", cond:"condition/regalec_meteo.png", heure:"condition/regalec_heure.png"},
    {name:"Red Mullet", bg:"condition/rouget_barbet_lieu.png", cond:"condition/rouget_barbet_meteo.png", heure:"condition/rouget_barbet_heure.png"},
    {name:"Dogfish", bg:"condition/roussette_lieu.png", cond:"condition/roussette_meteo.png", heure:"condition/roussette_heure.png"},
    {name:"White Zander", bg:"condition/sandre_blanc_lieu.png", cond:"condition/sandre_blanc_meteo.png", heure:"condition/sandre_blanc_heure.png"},
    {name:"Atlantic Salmon", bg:"condition/saumon_atlantique_lieu.png", cond:"condition/saumon_atlantique_meteo.png", heure:"condition/saumon_atlantique_heure.png"},
    {name:"Chum Salmon", bg:"condition/saumon_keta_lieu.png", cond:"condition/saumon_keta_meteo.png", heure:"condition/saumon_keta_heure.png"},
    {name:"Horse Mackerel", bg:"condition/saurel_lieu.png", cond:"condition/saurel_meteo.png", heure:"condition/saurel_heure.png"},
    {name:"Sardine", bg:"condition/sardine_lieu.png", cond:"condition/sardine_meteo.png", heure:"condition/sardine_heure.png"},
    {name:"Cuttlefish", bg:"condition/seiche_europeenne_lieu.png", cond:"condition/seiche_europeenne_meteo.png", heure:"condition/seiche_europeenne_heure.png"},
    {name:"Wels Catfish", bg:"condition/silure_europeen_lieu.png", cond:"condition/silure_europeen_meteo.png", heure:"condition/silure_europeen_heure.png"},
    {name:"Golden Tench", bg:"condition/tanche_doree_lieu.png", cond:"condition/tanche_doree_meteo.png", heure:"condition/tanche_doree_heure.png"},
    {name:"Tadpole", bg:"condition/tetard_lieu.png", cond:"condition/tetard_meteo.png", heure:"condition/tetard_heure.png"},
    {name:"Tilapia", bg:"condition/tilapia_lieu.png", cond:"condition/tilapia_meteo.png", heure:"condition/tilapia_heure.png"},
    {name:"Turbot", bg:"condition/turbot_lieu.png", cond:"condition/turbot_meteo.png", heure:"condition/turbot_heure.png"},
    {name:"Minnow", bg:"condition/vairon_lieu.png", cond:"condition/vairon_meteo.png", heure:"condition/vairon_heure.png"},
    {name:"Zingel Streber", bg:"condition/zingel_streber_lieu.png", cond:"condition/zingel_streber_meteo.png", heure:"condition/zingel_streber_heure.png"}
];

// 9. BUGS
const bugList = [
    {name:"Actias neidhoederi", bg:"condition/actias_neidhoederi_lieu.png", cond:"condition/actias_neidhoederi_meteo.png", heure:"condition/actias_neidhoederi_heure.png"},
    {name:"Holly Blue", bg:"condition/azure_de_porcelaine_lieu.png", cond:"condition/azure_de_porcelaine_meteo.png", heure:"condition/azure_de_porcelaine_heure.png"},
    {name:"Bumblebee", bg:"condition/bourdon_lieu.png", cond:"condition/bourdon_meteo.png", heure:"condition/bourdon_heure.png"},
    {name:"Blue Star Flower Beetle", bg:"condition/cetoine_etoilee_bleue_lieu.png", cond:"condition/cetoine_etoilee_bleue_meteo.png", heure:"condition/cetoine_etoilee_bleue_heure.png"},
    {name:"Green Tiger Beetle", bg:"condition/cicindele_verte_lieu.png", cond:"condition/cicindele_verte_meteo.png", heure:"condition/cicindele_verte_heure.png"},
    {name:"Gonepteryx aspasia", bg:"condition/citron_aspasia_lieu.png", cond:"condition/citron_aspasia_meteo.png", heure:"condition/citron_aspasia_heure.png"},
    {name:"7-Spot Ladybird", bg:"condition/coccinelle_a_sept_points_lieu.png", cond:"condition/coccinelle_a_sept_points_meteo.png", heure:"condition/coccinelle_a_sept_points_heure.png"},
    {name:"Asian Ladybeetle", bg:"condition/coccinelle_asiatique_lieu.png", cond:"condition/coccinelle_asiatique_meteo.png", heure:"condition/coccinelle_asiatique_heure.png"},
    {name:"Asparagus Beetle", bg:"condition/criocere_de_lasperge_lieu.png", cond:"condition/criocere_de_lasperge_meteo.png", heure:"condition/criocere_de_lasperge_heure.png"},
    {name:"Robust-legged Grasshopper", bg:"condition/criquet_aux_pattes_massives_lieu.png", cond:"condition/criquet_aux_pattes_massives_meteo.png", heure:"condition/criquet_aux_pattes_massives_heure.png"},
    {name:"Large Damselfly", bg:"condition/grand_agrion_lieu.png", cond:"condition/grand_agrion_meteo.png", heure:"condition/grand_agrion_heure.png"},
    {name:"Spotted Dragonfly", bg:"condition/libellule_tachetee_lieu.png", cond:"condition/libellule_tachetee_meteo.png", heure:"condition/libellule_tachetee_heure.png"},
    {name:"Red-ringed Butterfly", bg:"condition/papillon_a_anneaux_rouges_lieu.png", cond:"condition/papillon_a_anneaux_rouges_meteo.png", heure:"condition/papillon_a_anneaux_rouges_heure.png"},
    {name:"Red-necked Butterfly", bg:"condition/papillon_a_col_rouge_lieu.png", cond:"condition/papillon_a_col_rouge_meteo.png", heure:"condition/papillon_a_col_rouge_heure.png"},
    {name:"White Butterfly", bg:"condition/papillon_blanc_lieu.png", cond:"condition/papillon_blanc_meteo.png", heure:"condition/papillon_blanc_heure.png"},
    {name:"Golden Butterfly", bg:"condition/papillon_dore_lieu.png", cond:"condition/papillon_dore_meteo.png", heure:"condition/papillon_dore_heure.png"},
    {name:"Parnassian", bg:"condition/parnassien_lieu.png", cond:"condition/parnassien_meteo.png", heure:"condition/parnassien_heure.png"},
    {name:"Green-veined White", bg:"condition/pieride_du_cresson_lieu.png", cond:"condition/pieride_du_cresson_meteo.png", heure:"condition/pieride_du_cresson_heure.png"},
    {name:"Picasso Bug", bg:"condition/punaise_picasso_lieu.png", cond:"condition/punaise_picasso_meteo.png", heure:"condition/punaise_picasso_heure.png"},
    {name:"Pyrochroa", bg:"condition/pyrochroa_lieu.png", cond:"condition/pyrochroa_meteo.png", heure:"condition/pyrochroa_heure.png"},
    {name:"Firebug", bg:"condition/pyrrhocoris_apterus_lieu.png", cond:"condition/pyrrhocoris_apterus_meteo.png", heure:"condition/pyrrhocoris_apterus_heure.png"},
    {name:"Oasis Grasshopper", bg:"condition/sauterelle_de_loasis_lieu.png", cond:"condition/sauterelle_de_loasis_meteo.png", heure:"condition/sauterelle_de_loasis_heure.png"},
    {name:"Unicorn Beetle", bg:"condition/scarabee_unicorne_lieu.png", cond:"condition/scarabee_unicorne_meteo.png", heure:"condition/scarabee_unicorne_heure.png"}
];

// 10. BIRDS
const birdList = [
    {name:"Blue-and-yellow Macaw", bg:"condition/ara_bleu_et_jaune_lieu.png", cond:"condition/ara_bleu_et_jaune_meteo.png", heure:"condition/ara_bleu_et_jaune_heure.png"},
    {name:"Red-and-green Macaw", bg:"condition/ara_rouge_et_vert_lieu.png", cond:"condition/ara_rouge_et_vert_meteo.png", heure:"condition/ara_rouge_et_vert_heure.png"},
    {name:"Indigo Macaw", bg:"condition/ara_indigo_lieu.png", cond:"condition/ara_indigo_meteo.png", heure:"condition/ara_indigo_heure.png"},
    {name:"White Wagtail", bg:"condition/bergeronnette_grise_lieu.png", cond:"condition/bergeronnette_grise_meteo.png", heure:"condition/bergeronnette_grise_heure.png"},
    {name:"Bullfinch", bg:"condition/bouvreuil_lieu.png", cond:"condition/bouvreuil_meteo.png", heure:"condition/bouvreuil_heure.png"},
    {name:"Red-bellied Bullfinch", bg:"condition/bouvreuil_a_ventre_rouge_lieu.png", cond:"condition/bouvreuil_a_ventre_rouge_meteo.png", heure:"condition/bouvreuil_a_ventre_rouge_heure.png"},
    {name:"Green-headed Tanager", bg:"condition/calliste_septicolore_lieu.png", cond:"condition/calliste_septicolore_meteo.png", heure:"condition/calliste_septicolore_heure.png"},
    {name:"White-headed Duck", bg:"condition/canard_a_tete_blanche_lieu.png", cond:"condition/canard_a_tete_blanche_meteo.png", heure:"condition/canard_a_tete_blanche_heure.png"},
    {name:"Mallard", bg:"condition/canard_colvert_lieu.png", cond:"condition/canard_colvert_meteo.png", heure:"condition/canard_colvert_heure.png"},
    {name:"Wigeon", bg:"condition/canard_siffleur_lieu.png", cond:"condition/canard_siffleur_meteo.png", heure:"condition/canard_siffleur_heure.png"},
    {name:"Red-crested Cardinal", bg:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_lieu.png", cond:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_meteo.png", heure:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_heure.png"},
    {name:"Jambu Fruit Dove", bg:"condition/colombe_jambu_lieu.png", cond:"condition/colombe_jambu_meteo.png", heure:"condition/colombe_jambu_heure.png"},
    {name:"Zebra Finch", bg:"condition/diamant_mandarin_lieu.png", cond:"condition/diamant_mandarin_meteo.png", heure:"condition/diamant_mandarin_heure.png"},
    {name:"King Eider", bg:"condition/eider_royal_lieu.png", cond:"condition/eider_royal_meteo.png", heure:"condition/eider_royal_heure.png"},
    {name:"White-bellied Pheasant", bg:"condition/faisan_a_ventre_blanc_lieu.png", cond:"condition/faisan_a_ventre_blanc_meteo.png", heure:"condition/faisan_a_ventre_blanc_heure.png"},
    {name:"Red-footed Falcon", bg:"condition/faucon_a_pattes_rouges_lieu.png", cond:"condition/faucon_a_pattes_rouges_meteo.png", heure:"condition/faucon_a_pattes_rouges_heure.png"},
    {name:"Peregrine Falcon", bg:"condition/faucon_pelerin_lieu.png", cond:"condition/faucon_pelerin_meteo.png", heure:"condition/faucon_pelerin_heure.png"},
    {name:"Red Falcon", bg:"condition/faucon_rouge_lieu.png", cond:"condition/faucon_rouge_meteo.png", heure:"condition/faucon_rouge_heure.png"},
    {name:"American Flamingo", bg:"condition/flamant_rose_americain_lieu.png", cond:"condition/flamant_rose_americain_meteo.png", heure:"condition/flamant_rose_americain_heure.png"},
    {name:"Chaffinch", bg:"condition/fringilla_coelebs_lieu.png", cond:"condition/fringilla_coelebs_meteo.png", heure:"condition/fringilla_coelebs_heure.png"},
    {name:"Verditer Flycatcher", bg:"condition/gobemouche_vertdegris_lieu.png", cond:"condition/gobemouche_vertdegris_meteo.png", heure:"condition/gobemouche_vertdegris_heure.png"},
    {name:"Gull", bg:"condition/goeland_lieu.png", cond:"condition/goeland_meteo.png", heure:"condition/goeland_heure.png"},
    {name:"Golden Oriole", bg:"condition/golden_oriole_lieu.png", cond:"condition/golden_oriole_meteo.png", heure:"condition/golden_oriole_heure.png"},
    {name:"Eurasian Eagle-Owl", bg:"condition/grand_duc_deurope_lieu.png", cond:"condition/grand_duc_deurope_meteo.png", heure:"condition/grand_duc_deurope_heure.png"},
    {name:"Greater Flamingo", bg:"condition/grand_flamant_lieu.png", cond:"condition/grand_flamant_meteo.png", heure:"condition/grand_flamant_heure.png"},
    {name:"Great Spotted Woodpecker", bg:"condition/grand_pic_lieu.png", cond:"condition/grand_pic_meteo.png", heure:"condition/grand_pic_heure.png"},
    {name:"Hawfinch", bg:"condition/grosbec_lieu.png", cond:"condition/grosbec_meteo.png", heure:"condition/grosbec_heure.png"},
    {name:"European Bee-eater", bg:"condition/guepier_deurope_lieu.png", cond:"condition/guepier_deurope_meteo.png", heure:"condition/guepier_deurope_heure.png"},
    {name:"Smew", bg:"condition/harle_piette_lieu.png", cond:"condition/harle_piette_meteo.png", heure:"condition/harle_piette_heure.png"},
    {name:"Long-eared Owl", bg:"condition/hibou_moyen_duc_lieu.png", cond:"condition/hibou_moyen_duc_meteo.png", heure:"condition/hibou_moyen_duc_heure.png"},
    {name:"Golden Bowerbird", bg:"condition/jardinier_a_tete_jaune_lieu.png", cond:"condition/jardinier_a_tete_jaune_meteo.png", heure:"condition/jardinier_a_tete_jaune_heure.png"},
    {name:"White-backed Linnet", bg:"condition/linotte_a_dos_blanc_lieu.png", cond:"condition/linotte_a_dos_blanc_meteo.png", heure:"condition/linotte_a_dos_blanc_heure.png"},
    {name:"Eastern Bluebird", bg:"condition/merle_bleu_de_lest_lieu.png", cond:"condition/merle_bleu_de_lest_meteo.png", heure:"condition/merle_bleu_de_lest_heure.png"},
    {name:"Silver-throated Tit", bg:"condition/mesange_a_menton_argent_lieu.png", cond:"condition/mesange_a_menton_argent_meteo.png", heure:"condition/mesange_a_menton_argent_heure.png"},
    {name:"Blue Tit", bg:"condition/mesange_bleue_lieu.png", cond:"condition/mesange_bleue_meteo.png", heure:"condition/mesange_bleue_heure.png"},
    {name:"Yellow-bellied Flycatcher", bg:"condition/moucherolle_a_ventre_jaune_lieu.png", cond:"condition/moucherolle_a_ventre_jaune_meteo.png", heure:"condition/moucherolle_a_ventre_jaune_heure.png"},
    {name:"Seagull", bg:"condition/mouette_lieu.png", cond:"condition/mouette_meteo.png", heure:"condition/mouette_heure.png"},
    {name:"Bearded Reedling", bg:"condition/panure_a_moustache_lieu.png", cond:"condition/panure_a_moustache_meteo.png", heure:"condition/panure_a_moustache_heure.png"},
    {name:"White Peacock", bg:"condition/paon_blanc_lieu.png", cond:"condition/paon_blanc_meteo.png", heure:"condition/paon_blanc_heure.png"},
    {name:"Blue Peacock", bg:"condition/paon_bleu_lieu.png", cond:"condition/paon_bleu_meteo.png", heure:"condition/paon_bleu_heure.png"},
    {name:"Black Peacock", bg:"condition/paon_noir_lieu.png", cond:"condition/paon_noir_meteo.png", heure:"condition/paon_noir_heure.png"},
    {name:"Green Peacock", bg:"condition/paon_vert_lieu.png", cond:"condition/paon_vert_meteo.png", heure:"condition/paon_vert_heure.png"},
    {name:"Lesser Flamingo", bg:"condition/petit_flamant_lieu.png", cond:"condition/petit_flamant_meteo.png", heure:"condition/petit_flamant_heure.png"},
    {name:"Woodchat Shrike", bg:"condition/piegrieche_a_tete_rousse_lieu.png", cond:"condition/piegrieche_a_tete_rousse_meteo.png", heure:"condition/piegrieche_a_tete_rousse_heure.png"},
    {name:"Golden Fruit Dove", bg:"condition/pigeon_aux_fruits_dor_lieu.png", cond:"condition/pigeon_aux_fruits_dor_meteo.png", heure:"condition/pigeon_aux_fruits_dor_heure.png"},
    {name:"Yellow-eyed Pigeon", bg:"condition/pigeon_aux_yeux_jaunes_lieu.png", cond:"condition/pigeon_aux_yeux_jaunes_meteo.png", heure:"condition/pigeon_aux_yeux_jaunes_heure.png"},
    {name:"Stock Dove", bg:"condition/pigeon_colombin_lieu.png", cond:"condition/pigeon_colombin_meteo.png", heure:"condition/pigeon_colombin_heure.png"},
    {name:"Wonga Pigeon", bg:"condition/pigeon_de_wonga_lieu.png", cond:"condition/pigeon_de_wonga_meteo.png", heure:"condition/pigeon_de_wonga_heure.png"},
    {name:"Pink Pigeon", bg:"condition/pigeon_rose_lieu.png", cond:"condition/pigeon_rose_meteo.png", heure:"condition/pigeon_rose_heure.png"},
    {name:"Finch", bg:"condition/pinson_lieu.png", cond:"condition/pinson_meteo.png", heure:"condition/pinson_heure.png"},
    {name:"Robin", bg:"condition/rougegorge_lieu.png", cond:"condition/rougegorge_meteo.png", heure:"condition/rougegorge_heure.png"},
    {name:"Nuthatch", bg:"condition/sittelle_lieu.png", cond:"condition/sittelle_meteo.png", heure:"condition/sittelle_heure.png"},
    {name:"Tern", bg:"condition/sterne_lieu.png", cond:"condition/sterne_meteo.png", heure:"condition/sterne_heure.png"},
    {name:"White Tern", bg:"condition/sterne_blanche_lieu.png", cond:"condition/sterne_blanche_meteo.png", heure:"condition/sterne_blanche_heure.png"},
    {name:"Ruddy Shelduck", bg:"condition/tadorne_casarca_lieu.png", cond:"condition/tadorne_casarca_meteo.png", heure:"condition/tadorne_casarca_heure.png"},
    {name:"Grey-headed Dove", bg:"condition/tourterelle_a_tete_grise_lieu.png", cond:"condition/tourterelle_a_tete_grise_meteo.png", heure:"condition/tourterelle_a_tete_grise_heure.png"},
    {name:"Collared Dove", bg:"condition/tourterelle_grise_lieu.png", cond:"condition/tourterelle_grise_meteo.png", heure:"condition/tourterelle_grise_heure.png"},
    {name:"Spotted Dove", bg:"condition/tourterelle_tigrine_lieu.png", cond:"condition/tourterelle_tigrine_meteo.png", heure:"condition/tourterelle_tigrine_heure.png"},
    {name:"Wren", bg:"condition/troglodyte_lieu.png", cond:"condition/troglodyte_meteo.png", heure:"condition/troglodyte_heure.png"}
];

// 11. QUIZ (English Questions)
const QUIZ_DATA = [
    { q: "Who is the village guide?", o: ["Albert Jr.", "Barnabé", "Eric"], a: 0 },
    { q: "Where can you find the Acantharchus pomotis?", o: ["Calm Sea", "Forest Lake", "Aurora River"], a: 0 },
    { q: "Which NPC manages discoveries?", o: ["The Collector", "Bob", "Massimo"], a: 0 },
    { q: "What weather creates a rainbow?", o: ["Storm", "Fog", "Sun after rain"], a: 2 },
    { q: "Where is the Fishing Village located?", o: ["North-East", "South-West", "East"], a: 1 },
    { q: "The Actias neidhoederi is:", o: ["Morning", "Diurnal (Day)", "Nocturnal (Night)"], a: 2 },
    { q: "Where does the Capybara live?", o: ["The Ruins", "Diving Board", "Beach"], a: 0 },
    { q: "Who sells animals (dogs)?", o: ["Vernie", "Joan", "Andrew"], a: 1 },
    { q: "Where can you catch the Oarfish?", o: ["Rivers", "Lakes", "Ocean"], a: 2 },
    { q: "Where is the thermal area?", o: ["North", "South", "West"], a: 0 },
    { q: "The Unicorn Beetle lives in:", o: ["Oriental Dock", "Fields", "Forest"], a: 0 },
    { q: "The Indigo Macaw is a:", o: ["Fish", "Bug", "Bird"], a: 2 },
    { q: "The Butterfly Carp lives in:", o: ["Fresh water", "Salt water", "Meadow Lake"], a: 2 },
    { q: "Where is the NPC Will located?", o: ["Near the sea", "In the mountains", "In the forest"], a: 0 },
    { q: "Color of the FISH button?", o: ["Green", "Blue", "Orange"], a: 1 },
    { q: "The Bumblebee lives in:", o: ["Lakes", "Flower Fields", "Caves"], a: 1 },
    { q: "The Otter is found at:", o: ["Lighthouse", "Fishing Village", "Ruins"], a: 1 },
    { q: "The Panda lives near:", o: ["Diving Board", "Village", "Dock"], a: 0 },
    { q: "The Smelt lives in:", o: ["Meadow Lake", "Upper Lake", "Ocean"], a: 0 },
    { q: "Annie is located at:", o: ["Central Plaza", "Beach", "Forest"], a: 0 },
    { q: "The Llama lives at:", o: ["Purple Beach", "Mountain", "River"], a: 0 },
    { q: "Rate out of 20 for the map?", o: ["5", "0", "20"], a: 2 },
    { q: "The Blue Noble Crayfish lives in:", o: ["Forest Lake", "Ocean", "Calm Sea"], a: 0 },
    { q: "Whale Mountain is to the:", o: ["South", "North", "West"], a: 2 },
    { q: "Maptopia is used to:", o: ["Sell items", "Locate resources", "Replace the game"], a: 1 },
    { q: "The White Wagtail is a:", o: ["Bird", "Fish", "Resident"], a: 1 },
    { q: "The Deer lives in:", o: ["Beach", "Oak Forest", "Town"], a: 1 },
    { q: "The Gonepteryx aspasia is a:", o: ["Fruit", "Bug", "Fish"], a: 1 },
    { q: "The Oriental Dock is to the:", o: ["North", "East", "South"], a: 1 },
    { q: "Bob is a:", o: ["Animal", "NPC", "Place"], a: 1 }
];