// --- 中文数据 (data-ch.js) ---

// 1. 界面文本 (UI)
const TEXTS = {
    title: "MAPTOPIA CH",
    enterBtn: "✨ 进入地图 ✨",
    menu: {
        pnj: "NPC",
        animals: "动物",
        bus: "巴士",
        shops: "商店",
        places: "地点",
        fish: "鱼类",
        bugs: "昆虫",
        birds: "鸟类",
        resources: "资源"
    },
    chat: {
        success: "✅ 发送成功!",
        error: "❌ 发送错误.",
        incomplete: "⚠️ 请填写所有字段.",
        wait: "发送中..."
    },
    quiz: {
        success: "✅ 正确!",
        error: "❌ 错误!",
        finishTitle: "🏆 专家认证!",
        finishText: "你对 Heartopia 了如指掌。",
        quitBtn: "退出测验"
    },
    like: {
        thankyou: "谢谢!",
        already: "你已经投过票了!"
    }
};

// 2. NPC 列表
const PNJ_DATA = [
    [-471, 501, "鲍勃", "pnj/bob.png"],
    [-526, 499, "阿塔拉", "pnj/atara.png"],
    [-478, 493, "收藏家", "pnj/collectioneur.png"],
    [-469, 488, "多萝西", "pnj/dorothée.png"],
    [-446, 493, "马西莫", "pnj/massimo.png"],
    [-412, 418, "卡钦", "pnj/ka ching.png"],
    [-399, 591, "安德鲁", "pnj/andrew.png"],
    [-259, 522, "埃里克", "pnj/eric.png"],
    [-456, 549, "瓦尼亚", "pnj/vanya.png"],
    [-502, 582, "浪花", "pnj/naniwa.png"],
    [-502, 519, "琼夫人", "pnj/mme joan.png"],
    [-807, 419, "威尔", "pnj/will.png"],
    [-355, 809, "帕蒂", "pnj/patti.png"],
    [-653, 225, "弗尼", "pnj/vernie.png"],
    [-498, 526, "贝利 J", "pnj/bayleyj.png"],
    [-528.3, 560.3, "布兰克", "pnj/blanc.png"],
    [-499.8, 499.0, "安妮", "pnj/annie.png"],
    [-532.4, 634.8, "小阿尔伯特", "pnj/albert jr.png"],
    [-734.8, 445.8, "比尔", "pnj/bill.png"],
    [-509.4, 414, "多丽丝 (雨)", "pnj/doris.png"]
];

// 3. 巴士站
const BUS_DATA = [
    ["西郊",[-533,340]], ["郊区村庄",[-519,639]], ["渔夫村",[-654,479]], 
    ["花田",[-532,218]], ["温泉山",[-222,512]], ["北郊",[-373,480]], 
    ["中央广场",[-497,481]], ["森林",[-500,798]]
];

// 4. 商店
const SHOP_DATA = [
    [-472,487,"服装店","vetement.png"],[-474,503,"家具店","Meuble.png"],
    [-496.4,520.6,"宠物店","chien.png"],[-440,467,"书店","Librairie.png"]
];

// 5. 动物
const ANIMAL_DATA = [
    {pos: [-691, 783], name: "熊猫", img: "panda.png", radius: 60},
    {pos: [-184, 291], name: "水豚", img: "capybara.png", radius: 50},
    {pos: [-533, 340], name: "兔子", img: "lapin.png", radius: 40},
    {pos: [-649, 185], name: "狐狸", img: "renard.png", radius: 70},
    {pos: [-737, 512], name: "水獭", img: "loutre.png", radius: 40},
    {pos: [-354.3, 277.3], name: "水貂", img: "vison.png", radius: 10},
    {pos: [-531, 805], name: "鹿", img: "cerf.png", radius: 60},
    {pos: [-725, 208], name: "羊驼", img: "lama.png", radius: 50}
];

// 6. 地点
const LIEUX_DATA = [
    {pos:[-538,492], name:"中央广场", type:"label-ville", startOn:true}, 
    {pos:[-692,506], name:"渔夫村", type:"label-ville", startOn:true}, 
    {pos:[-438,513], name:"居民街", type:"label-ville", startOn:true}, 
    {pos:[-649,185], name:"花田", type:"label-ville", startOn:true}, 
    {pos:[-440,184], name:"鲸鱼山", type:"label-ville", startOn:true}, 
    {pos:[-184,291], name:"遗迹", type:"label-ville", startOn:true}, 
    {pos:[-223,501], name:"温泉山", type:"label-ville", startOn:true}, 
    {pos:[-228,627], name:"岩石悬崖", type:"label-ville", startOn:true}, 
    {pos:[-531,805], name:"橡树林", type:"label-ville", startOn:true}, 
    {pos:[-494,429], name:"艺术街", type:"label-ville", startOn:true}, 
    {pos:[-510,558], name:"花园街", type:"label-ville", startOn:true}, 
    {pos:[-736,602], name:"东码头", type:"label-ville", startOn:true}, 
    {pos:[-690,402], name:"码头", type:"label-ville", startOn:true}, 
    {pos:[-780,387], name:"灯塔", type:"label-ville", startOn:true}, 
    {pos:[-691,783], name:"跳台", type:"label-ville", startOn:true}, 
    {pos:[-338,933], name:"森林岛", type:"label-ville", startOn:true}, 
    {pos:[-587,406], name:"郊区", type:"label-ville", startOn:true}, 
    {pos:[-725,208], name:"紫色海滩", type:"label-ville", startOn:true}, 
    {pos:[-783,478], name:"平静海域", type:"label-eau", startOn:true}, 
    {pos:[-534,92], name:"鲸鱼海", type:"label-eau", startOn:true}, 
    {pos:[-68,497], name:"古老海域", type:"label-eau", startOn:true}, 
    {pos:[-536,232], name:"草原湖", type:"label-eau", startOn:true}, 
    {pos:[-337,319], name:"极光河", type:"label-eau", startOn:true}, 
    {pos:[-176,394], name:"火山湖", type:"label-eau", startOn:true}, 
    {pos:[-265,537], name:"温泉湖", type:"label-eau", startOn:true}, 
    {pos:[-344,652], name:"浅河", type:"label-eau", startOn:true}, 
    {pos:[-598,748], name:"森林湖", type:"label-eau", startOn:true}, 
    {pos:[-431,774], name:"上森林湖", type:"label-eau", startOn:true}, 
    {pos:[-608,481], name:"郊区湖", type:"label-eau", startOn:true}, 
    {pos:[-669,368], name:"宁静河", type:"label-eau", startOn:true}, 
    {pos:[-674,627], name:"巨树河", type:"label-eau", startOn:true}, 
    {pos:[-600,600], name:"风车花田", type:"label-ville", startOn:true}, 
    {pos:[-670,450], name:"东浮桥", type:"label-ville", startOn:true}
];

// 7. 资源
const resourcesData = {
    "覆盆子": { icon: "resource/framboise.png", positions: [[-680.8, 330.9], [-668.5, 352.1], [-667.9, 268.5], [-648.3, 288.6], [-613.5, 317.4], [-602.8, 274.5], [-617.6, 211.6], [-571.5, 254.4], [-538.9, 208.6], [-527.8, 251.6], [-535.8, 288.3], [-503.1, 242.9], [-495, 222.4], [-453.8, 222.4], [-438.6, 246], [-395, 247.4], [-387.1, 269.5]] },
    "蓝莓": { icon: "resource/myrtille.png", positions: [[-642.9, 371.9], [-631.9, 368.4], [-628.5, 365.5], [-606.8, 350.3], [-602.5, 342.3], [-590.1, 334.1], [-575.6, 332.1], [-562.1, 330], [-544.9, 324.5], [-518.4, 320.3], [-515.9, 320.5], [-500.8, 321.1], [-479.3, 328.6], [-468.3, 320], [-437.3, 313.9], [-411.4, 311.4], [-400.3, 311.4], [-379.5, 304.1], [-327.4, 352], [-313.6, 339], [-328.6, 371.5], [-324.4, 389.3], [-297.9, 410.8], [-271.6, 395.4], [-319.9, 413.5], [-330.4, 421.6], [-333.4, 450], [-338.6, 468.6], [-297.4, 484.4], [-349, 489.4], [-356.5, 499.3], [-360.4, 526.4], [-355.5, 545.1], [-352.9, 565.9], [-316, 558.1], [-363.6, 578.4], [-365.3, 609], [-360.9, 628.1], [-343, 634], [-388, 655.4], [-400.9, 654.3], [-421.9, 656.4], [-444.1, 670.6], [-462.5, 654], [-476.8, 654.6], [-491.6, 656.3], [-506.4, 672.4], [-525.4, 688], [-542.6, 650], [-559.3, 644.9], [-575.6, 651], [-597.8, 643.8], [-604.8, 633.8], [-627.9, 619.4]] },
    "苹果": { icon: "resource/pomme.png", positions: [[-356.3, 493], [-365.4, 560.1], [-362.4, 581], [-324.6, 570.1], [-296, 610.3], [-365.6, 619.5], [-362.8, 628.5], [-393.5, 654.8], [-420.6, 653.3], [-436.1, 665.4], [-444.4, 685.1], [-436.6, 697.5], [-458.4, 744.9], [-505, 677.3], [-494.5, 657], [-459.8, 653.6], [-530.1, 677.9], [-540.1, 648.6], [-592.8, 676.6], [-606.9, 634.1], [-629.3, 623]] },
    "大树": { icon: "resource/grand arbre.png", positions: [[-612, 424.5], [-641.8, 369], [-351, 329.5], [-414.3, 337.1], [-396.3, 608.9], [-376.3, 624], [-616, 593.6], [-672.3, 642]] },
    "石头": { icon: "resource/pierre.png", positions: [[-615.9, 316], [-641.5, 278.8], [-558.4, 257.4], [-535, 292], [-499.5, 241.1], [-466.8, 283.1], [-407.1, 244.1], [-284, 402.8], [-254.6, 367.9], [-309.4, 479.1], [-263, 466.6], [-289.1, 544.6], [-315.5, 567.9], [-298.6, 625.4], [-391.3, 726.9], [-443.6, 697], [-468.6, 733.8], [-519, 714.9], [-564.9, 732.8], [-605.1, 680.3], [-673.9, 684.1]] },
    "橙子": { icon: "resource/orange.png", positions: [[-650.1, 370.9], [-639.5, 372], [-607.3, 351.4], [-602.9, 343.5], [-588.6, 336.6], [-559.6, 329.5], [-542.1, 324.8], [-515, 319.5], [-470.5, 321], [-461.4, 271.5], [-410.8, 314], [-397.3, 310.1], [-310.9, 339.3], [-327.6, 373.9], [-324.9, 391.9], [-295.4, 411.1], [-330.4, 420.9], [-333.8, 452.9]] },
    "牛肝菌": { icon: "resource/cépes de bordeaux.png", positions: [[-615, 796.9], [-620, 778.1], [-610.6, 759.9], [-634.9, 745.5], [-650, 773.5], [-639, 800.6], [-543.5, 776.3], [-523.6, 777], [-524.3, 818.9], [-479.9, 780.8], [-464.3, 775.6], [-472.1, 801], [-477.3, 825.8], [-438.4, 789.3], [-410.5, 776.8], [-404.1, 794.1], [-415.8, 799.1]] },
    "黑松露": { icon: "resource/truffes noires.png", positions: [[-358.1, 911.1], [-357.4, 926.1], [-340.4, 913.6], [-325.8, 920], [-342.1, 956.5], [-363.3, 961.8]] },
    "香菇": { icon: "resource/Lentins du chene.png", positions: [[-772.3, 411.8], [-763.5, 397], [-736.8, 426.1], [-717.3, 446.8], [-705.8, 432.1], [-667.1, 462.5], [-666.6, 482.5], [-698.5, 491.8], [-698.3, 520.5], [-690.3, 542.6], [-686.4, 553.1], [-719.8, 546.6], [-724.8, 555.3], [-707.5, 575.9], [-714.9, 596.3]] },
    "蘑菇": { icon: "resource/mousseron.png", positions: [[-676.3, 271.5], [-667.8, 264], [-686.3, 260.8], [-706.3, 253.5], [-632.8, 247.3], [-601.3, 229.5], [-577.5, 242.8], [-553.5, 237.3], [-491.8, 177.8], [-480.5, 192.5], [-459.8, 225.8], [-440.3, 230.3], [-420.3, 202.8], [-408.3, 178.8]] },
    "平菇": { icon: "resource/pleurote.png", positions: [[-220.5, 355.3], [-207.5, 352.6], [-145.3, 303], [-162.5, 296], [-190.5, 294.3], [-210.3, 301.8], [-221.3, 310], [-214, 421.1], [-196.1, 428.4], [-174.4, 399.8], [-212.6, 470.8], [-232.5, 522.3], [-205.8, 512.4], [-194.9, 526.1], [-169, 510.6], [-167.9, 533.9], [-186, 547.6], [-189.3, 583.9]] }
};

// 8. 鱼类列表
const fishList = [
    {name:"欧鲌", bg:"condition/ablette_lieu.png", cond:"condition/ablette_meteo.png", heure:"condition/ablette_heure.png"},
    {name:"刺盖太阳鱼", bg:"condition/acantharchus_pomotis_lieu.png", cond:"condition/acantharchus_pomotis_meteo.png", heure:"condition/acantharchus_pomotis_heure.png"},
    {name:"欧洲鳗鲡", bg:"condition/anguille_europeenne_lieu.png", cond:"condition/anguille_europeenne_meteo.png", heure:"condition/anguille_europeenne_heure.png"},
    {name:"红带鳉", bg:"condition/aphyosemion_striatum_lieu.png", cond:"condition/aphyosemion_striatum_meteo.png", heure:"condition/aphyosemion_striatum_heure.png"},
    {name:"鲃鱼", bg:"condition/barbeau_lieu.png", cond:"condition/barbeau_meteo.png", heure:"condition/barbeau_heure.png"},
    {name:"小鲃", bg:"condition/barbillon_lieu.png", cond:"condition/barbillon_meteo.png", heure:"condition/barbillon_heure.png"},
    {name:"安康鱼", bg:"condition/baudroie_lieu.png", cond:"condition/baudroie_meteo.png", heure:"condition/baudroie_heure.png"},
    {name:"寄居蟹", bg:"condition/bernard_lhermite_lieu.png", cond:"condition/bernard_lhermite_meteo.png", heure:"condition/bernard_lhermite_heure.png"},
    {name:"河鳚", bg:"condition/blennie_de_riviere_lieu.png", cond:"condition/blennie_de_riviere_meteo.png", heure:"condition/blennie_de_riviere_heure.png"},
    {name:"鲣鱼", bg:"condition/bonite_lieu.png", cond:"condition/bonite_meteo.png", heure:"condition/bonite_heure.png"},
    {name:"斑点狗鱼", bg:"condition/brochet_tachete_lieu.png", cond:"condition/brochet_tachete_meteo.png", heure:"condition/brochet_tachete_heure.png"},
    {name:"白鲢", bg:"condition/carpe_argente_lieu.png", cond:"condition/carpe_argente_meteo.png", heure:"condition/carpe_argente_heure.png"},
    {name:"欧洲鲤鱼", bg:"condition/carpe_europeenne_lieu.png", cond:"condition/carpe_europeenne_meteo.png", heure:"condition/carpe_europeenne_heure.png"},
    {name:"蝴蝶鲤", bg:"condition/carpe_papillon_lieu.png", cond:"condition/carpe_papillon_meteo.png", heure:"condition/carpe_papillon_heure.png"},
    {name:"青鱼", bg:"condition/carpe_noire_lieu.png", cond:"condition/carpe_noire_meteo.png", heure:"condition/carpe_noire_heure.png"},
    {name:"杜父鱼", bg:"condition/chabot_lieu.png", cond:"condition/chabot_meteo.png", heure:"condition/chabot_heure.png"},
    {name:"银鲛", bg:"condition/chimere_argentee_lieu.png", cond:"condition/chimere_argentee_meteo.png", heure:"condition/chimere_argentee_heure.png"},
    {name:"彗星金鱼", bg:"condition/comete_coussut_lieu.png", cond:"condition/comete_coussut_meteo.png", heure:"condition/comete_coussut_heure.png"},
    {name:"溪蟹", bg:"condition/crabe_de_ruisseau_lieu.png", cond:"condition/crabe_de_ruisseau_meteo.png", heure:"condition/crabe_de_ruisseau_heure.png"},
    {name:"海虾", bg:"condition/crevette_de_la_mer_lieu.png", cond:"condition/crevette_de_la_mer_meteo.png", heure:"condition/crevette_de_la_mer_heure.png"},
    {name:"绿虾", bg:"condition/crevette_verte_lieu.png", cond:"condition/crevette_verte_meteo.png", heure:"condition/crevette_verte_heure.png"},
    {name:"贵族小龙虾", bg:"condition/ecrevisse_noble_lieu.png", cond:"condition/ecrevisse_noble_meteo.png", heure:"condition/ecrevisse_noble_heure.png"},
    {name:"蓝色贵族小龙虾", bg:"condition/ecrevisse_noble_bleue_lieu.png", cond:"condition/ecrevisse_noble_bleue_meteo.png", heure:"condition/ecrevisse_noble_bleue_heure.png"},
    {name:"黑线鳕", bg:"condition/eglefin_lieu.png", cond:"condition/eglefin_meteo.png", heure:"condition/eglefin_heure.png"},
    {name:"胡瓜鱼", bg:"condition/eperlan_lieu.png", cond:"condition/eperlan_meteo.png", heure:"condition/eperlan_heure.png"},
    {name:"费拉鱼", bg:"condition/fera_lieu.png", cond:"condition/fera_meteo.png", heure:"condition/fera_heure.png"},
    {name:"大口黑鲈", bg:"condition/grand_blackbasse_lieu.png", cond:"condition/grand_blackbasse_meteo.png", heure:"condition/grand_blackbasse_heure.png"},
    {name:"欧洲青蛙", bg:"condition/grenouille_europeenne_lieu.png", cond:"condition/grenouille_europeenne_meteo.png", heure:"condition/grenouille_europeenne_heure.png"},
    {name:"虾虎鱼", bg:"condition/gobie_lieu.png", cond:"condition/gobie_meteo.png", heure:"condition/gobie_heure.png"},
    {name:"鲂鮄", bg:"condition/grondin_perlon_lieu.png", cond:"condition/grondin_perlon_meteo.png", heure:"condition/grondin_perlon_heure.png"},
    {name:"海马", bg:"condition/hippocampe_lieu.png", cond:"condition/hippocampe_meteo.png", heure:"condition/hippocampe_heure.png"},
    {name:"多瑙哲罗鱼", bg:"condition/huchon_lieu.png", cond:"condition/huchon_meteo.png", heure:"condition/huchon_heure.png"},
    {name:"欧洲龙虾", bg:"condition/langouste_europeenne_lieu.png", cond:"condition/langouste_europeenne_meteo.png", heure:"condition/langouste_europeenne_heure.png"},
    {name:"花鳅", bg:"condition/loche_des_fleurs_lieu.png", cond:"condition/loche_des_fleurs_meteo.png", heure:"condition/loche_des_fleurs_heure.png"},
    {name:"岩鳅", bg:"condition/loche_des_rochers_lieu.png", cond:"condition/loche_des_rochers_meteo.png", heure:"condition/loche_des_rochers_heure.png"},
    {name:"江鳕", bg:"condition/lotte_lieu.png", cond:"condition/lotte_meteo.png", heure:"condition/lotte_heure.png"},
    {name:"大西洋鲭鱼", bg:"condition/maquereau_atlantique_lieu.png", cond:"condition/maquereau_atlantique_meteo.png", heure:"condition/maquereau_atlantique_heure.png"},
    {name:"贻贝", bg:"condition/moule_lieu.png", cond:"condition/moule_meteo.png", heure:"condition/moule_heure.png"},
    {name:"北极红点鲑", bg:"condition/omble_chevalier_lieu.png", cond:"condition/omble_chevalier_meteo.png", heure:"condition/omble_chevalier_heure.png"},
    {name:"石首鱼", bg:"condition/ombrine_lieu.png", cond:"condition/ombrine_meteo.png", heure:"condition/ombrine_heure.png"},
    {name:"佛罗伦萨鲷", bg:"condition/pagellus_bogaraveo_lieu.png", cond:"condition/pagellus_bogaraveo_meteo.png", heure:"condition/pagellus_bogaraveo_heure.png"},
    {name:"海鲈", bg:"condition/perche_de_mer_lieu.png", cond:"condition/perche_de_mer_meteo.png", heure:"condition/perche_de_mer_heure.png"},
    {name:"梅花鲈", bg:"condition/perche_de_prunier_lieu.png", cond:"condition/perche_de_prunier_meteo.png", heure:"condition/perche_de_prunier_heure.png"},
    {name:"河鲈", bg:"condition/perche_de_riviere_lieu.png", cond:"condition/perche_de_riviere_meteo.png", heure:"condition/perche_de_riviere_heure.png"},
    {name:"章鱼", bg:"condition/pieuvre_lieu.png", cond:"condition/pieuvre_meteo.png", heure:"condition/pieuvre_heure.png"},
    {name:"大西洋侏儒章鱼", bg:"condition/pieuvre_naine_atlantique_lieu.png", cond:"condition/pieuvre_naine_atlantique_meteo.png", heure:"condition/pieuvre_naine_atlantique_heure.png"},
    {name:"虎鱼", bg:"condition/poissontigre_a_ventre_rouge_lieu.png", cond:"condition/poissontigre_a_ventre_rouge_meteo.png", heure:"condition/poissontigre_a_ventre_rouge_heure.png"},
    {name:"欧鲽", bg:"condition/plie_europeenne_lieu.png", cond:"condition/plie_europeenne_meteo.png", heure:"condition/plie_europeenne_heure.png"},
    {name:"小丑鱼", bg:"condition/poissonclown_lieu.png", cond:"condition/poissonclown_meteo.png", heure:"condition/poissonclown_heure.png"},
    {name:"刺鱼", bg:"condition/poisson_epineux_lieu.png", cond:"condition/poisson_epineux_meteo.png", heure:"condition/poisson_epineux_heure.png"},
    {name:"河豚", bg:"condition/poissonglobe_de_riviere_lieu.png", cond:"condition/poissonglobe_de_riviere_meteo.png", heure:"condition/poissonglobe_de_riviere_heure.png"},
    {name:"金鱼", bg:"condition/poisson_rouge_lieu.png", cond:"condition/poisson_rouge_meteo.png", heure:"condition/poisson_rouge_heure.png"},
    {name:"带鱼", bg:"condition/poisson_ruban_lieu.png", cond:"condition/poisson_ruban_meteo.png", heure:"condition/poisson_ruban_heure.png"},
    {name:"红眼鱼", bg:"condition/poisson_a_yeux_rouges_lieu.png", cond:"condition/poisson_a_yeux_rouges_meteo.png", heure:"condition/poisson_a_yeux_rouges_heure.png"},
    {name:"皇带鱼", bg:"condition/regalec_lieu.png", cond:"condition/regalec_meteo.png", heure:"condition/regalec_heure.png"},
    {name:"羊鱼", bg:"condition/rouget_barbet_lieu.png", cond:"condition/rouget_barbet_meteo.png", heure:"condition/rouget_barbet_heure.png"},
    {name:"猫鲨", bg:"condition/roussette_lieu.png", cond:"condition/roussette_meteo.png", heure:"condition/roussette_heure.png"},
    {name:"白梭鲈", bg:"condition/sandre_blanc_lieu.png", cond:"condition/sandre_blanc_meteo.png", heure:"condition/sandre_blanc_heure.png"},
    {name:"大西洋鲑", bg:"condition/saumon_atlantique_lieu.png", cond:"condition/saumon_atlantique_meteo.png", heure:"condition/saumon_atlantique_heure.png"},
    {name:"大马哈鱼", bg:"condition/saumon_keta_lieu.png", cond:"condition/saumon_keta_meteo.png", heure:"condition/saumon_keta_heure.png"},
    {name:"竹荚鱼", bg:"condition/saurel_lieu.png", cond:"condition/saurel_meteo.png", heure:"condition/saurel_heure.png"},
    {name:"沙丁鱼", bg:"condition/sardine_lieu.png", cond:"condition/sardine_meteo.png", heure:"condition/sardine_heure.png"},
    {name:"欧洲乌贼", bg:"condition/seiche_europeenne_lieu.png", cond:"condition/seiche_europeenne_meteo.png", heure:"condition/seiche_europeenne_heure.png"},
    {name:"欧洲巨鲶", bg:"condition/silure_europeen_lieu.png", cond:"condition/silure_europeen_meteo.png", heure:"condition/silure_europeen_heure.png"},
    {name:"金丁鱥", bg:"condition/tanche_doree_lieu.png", cond:"condition/tanche_doree_meteo.png", heure:"condition/tanche_doree_heure.png"},
    {name:"蝌蚪", bg:"condition/tetard_lieu.png", cond:"condition/tetard_meteo.png", heure:"condition/tetard_heure.png"},
    {name:"罗非鱼", bg:"condition/tilapia_lieu.png", cond:"condition/tilapia_meteo.png", heure:"condition/tilapia_heure.png"},
    {name:"大菱鲆", bg:"condition/turbot_lieu.png", cond:"condition/turbot_meteo.png", heure:"condition/turbot_heure.png"},
    {name:"米诺鱼", bg:"condition/vairon_lieu.png", cond:"condition/vairon_meteo.png", heure:"condition/vairon_heure.png"},
    {name:"条纹金吉鲈", bg:"condition/zingel_streber_lieu.png", cond:"condition/zingel_streber_meteo.png", heure:"condition/zingel_streber_heure.png"}
];

// 9. 昆虫列表
const bugList = [
    {name:"白尾大黄蜂", bg:"condition/abeille_a_queue_blanche_lieu.png", cond:"condition/abeille_a_queue_blanche_meteo.png", heure:"condition/abeille_a_queue_blanche_heure.png"},
    {name:"蓝木蜂", bg:"condition/Abeille_charpentière_bleue_lieu.png", cond:"condition/Abeille_charpentière_bleue_meteo.png", heure:"condition/Abeille_charpentière_bleue_heure.png"},
    {name:"紫木蜂", bg:"condition/abeille_charpentiere_violette_lieu.png", cond:"condition/abeille_charpentiere_violette_meteo.png", heure:"condition/abeille_charpentiere_violette_heure.png"},
    {name:"长尾水青蛾", bg:"condition/actias_neidhoederi_lieu.png", cond:"condition/actias_neidhoederi_meteo.png", heure:"condition/actias_neidhoederi_heure.png"},
    {name:"琉璃灰蝶", bg:"condition/azure_de_porcelaine_lieu.png", cond:"condition/azure_de_porcelaine_meteo.png", heure:"condition/azure_de_porcelaine_heure.png"},
    {name:"熊蜂", bg:"condition/bourdon_lieu.png", cond:"condition/bourdon_meteo.png", heure:"condition/bourdon_heure.png"},
    {name:"虎天牛", bg:"condition/capricorne_tigre_lieu.png", cond:"condition/capricorne_tigre_meteo.png", heure:"condition/capricorne_tigre_heure.png"},
    {name:"蓝星花金龟", bg:"condition/cetoine_etoilee_bleue_lieu.png", cond:"condition/cetoine_etoilee_bleue_meteo.png", heure:"condition/cetoine_etoilee_bleue_heure.png"},
    {name:"绿虎甲", bg:"condition/cicindele_verte_lieu.png", cond:"condition/cicindele_verte_meteo.png", heure:"condition/cicindele_verte_heure.png"},
    {name:"蝉", bg:"condition/cigale_lieu.png", cond:"condition/cigale_meteo.png", heure:"condition/cigale_heure.png"},
    {name:"钩粉蝶", bg:"condition/citron_aspasia_lieu.png", cond:"condition/citron_aspasia_meteo.png", heure:"condition/citron_aspasia_heure.png"},
    {name:"七星瓢虫", bg:"condition/coccinelle_a_sept_points_lieu.png", cond:"condition/coccinelle_a_sept_points_meteo.png", heure:"condition/coccinelle_a_sept_points_heure.png"},
    {name:"异色瓢虫", bg:"condition/coccinelle_asiatique_lieu.png", cond:"condition/coccinelle_asiatique_meteo.png", heure:"condition/coccinelle_asiatique_heure.png"},
    {name:"芦笋叶甲", bg:"condition/criocere_de_lasperge_lieu.png", cond:"condition/criocere_de_lasperge_meteo.png", heure:"condition/criocere_de_lasperge_heure.png"},
    {name:"网翅蝗", bg:"condition/criquet_a_ailes_reticulees_lieu.png", cond:"condition/criquet_a_ailes_reticulees_meteo.png", heure:"condition/criquet_a_ailes_reticulees_heure.png"},
    {name:"粗腿蝗", bg:"condition/criquet_aux_pattes_massives_lieu.png", cond:"condition/criquet_aux_pattes_massives_meteo.png", heure:"condition/criquet_aux_pattes_massives_heure.png"},
    {name:"蚂蚁", bg:"condition/fourmi_lieu.png", cond:"condition/fourmi_meteo.png", heure:"condition/fourmi_heure.png"},
    {name:"大蟌", bg:"condition/grand_agrion_lieu.png", cond:"condition/grand_agrion_meteo.png", heure:"condition/grand_agrion_heure.png"},
    {name:"蟋蟀", bg:"condition/grillon_lieu.png", cond:"condition/grillon_meteo.png", heure:"condition/grillon_heure.png"},
    {name:"白尾蜻蜓", bg:"condition/libellule_a_queue_blanche_lieu.png", cond:"condition/libellule_a_queue_blanche_meteo.png", heure:"condition/libellule_a_queue_blanche_heure.png"},
    {name:"斑点蜻蜓", bg:"condition/libellule_tachetee_lieu.png", cond:"condition/libellule_tachetee_meteo.png", heure:"condition/libellule_tachetee_heure.png"},
    {name:"彩虹螳螂", bg:"condition/mante_arcenciel_lieu.png", cond:"condition/mante_arcenciel_meteo.png", heure:"condition/mante_arcenciel_heure.png"},
    {name:"巴布亚螳螂", bg:"condition/mante_papoue_lieu.png", cond:"condition/mante_papoue_meteo.png", heure:"condition/mante_papoue_heure.png"},
    {name:"豹纹蛱蝶", bg:"condition/melitee_leopard_lieu.png", cond:"condition/melitee_leopard_meteo.png", heure:"condition/melitee_leopard_heure.png"},
    {name:"孔雀蛱蝶", bg:"condition/paondujour_lieu.png", cond:"condition/paondujour_meteo.png", heure:"condition/paondujour_heure.png"},
    {name:"红环蝶", bg:"condition/papillon_a_anneaux_rouges_lieu.png", cond:"condition/papillon_a_anneaux_rouges_meteo.png", heure:"condition/papillon_a_anneaux_rouges_heure.png"},
    {name:"红领凤蝶", bg:"condition/papillon_a_col_rouge_lieu.png", cond:"condition/papillon_a_col_rouge_meteo.png", heure:"condition/papillon_a_col_rouge_heure.png"},
    {name:"粉蝶", bg:"condition/papillon_blanc_lieu.png", cond:"condition/papillon_blanc_meteo.png", heure:"condition/papillon_blanc_heure.png"},
    {name:"金凤蝶", bg:"condition/papillon_dore_lieu.png", cond:"condition/papillon_dore_meteo.png", heure:"condition/papillon_dore_heure.png"},
    {name:"白巫师夜蛾", bg:"condition/Papillon_sorcière_blanche_lieu.png", cond:"condition/Papillon_sorcière_blanche_meteo.png", heure:"condition/Papillon_sorcière_blanche_heure.png"},
    {name:"绢蝶", bg:"condition/parnassien_lieu.png", cond:"condition/parnassien_meteo.png", heure:"condition/parnassien_heure.png"},
    {name:"小斑粉蝶", bg:"condition/pieride_du_cresson_lieu.png", cond:"condition/pieride_du_cresson_meteo.png", heure:"condition/pieride_du_cresson_heure.png"},
    {name:"毕加索虫", bg:"condition/punaise_picasso_lieu.png", cond:"condition/punaise_picasso_meteo.png", heure:"condition/punaise_picasso_heure.png"},
    {name:"赤翅甲", bg:"condition/pyrochroa_lieu.png", cond:"condition/pyrochroa_meteo.png", heure:"condition/pyrochroa_heure.png"},
    {name:"红蝽", bg:"condition/pyrrhocoris_apterus_lieu.png", cond:"condition/pyrrhocoris_apterus_meteo.png", heure:"condition/pyrrhocoris_apterus_heure.png"},
    {name:"绿洲蝗", bg:"condition/sauterelle_de_loasis_lieu.png", cond:"condition/sauterelle_de_loasis_meteo.png", heure:"condition/sauterelle_de_loasis_heure.png"},
    {name:"粉红螽斯", bg:"condition/sauterelle_rose_lieu.png", cond:"condition/sauterelle_rose_meteo.png", heure:"condition/sauterelle_rose_heure.png"},
    {name:"独角仙", bg:"condition/scarabee_unicorne_lieu.png", cond:"condition/scarabee_unicorne_meteo.png", heure:"condition/scarabee_unicorne_heure.png"},
    {name:"紫蛱蝶", bg:"condition/Vanesse_violette_lieu.png", cond:"condition/Vanesse_violette_meteo.png", heure:"condition/Vanesse_violette_heure.png"}
];

// 10. 鸟类列表
const birdList = [
    {name:"蓝黄金刚鹦鹉", bg:"condition/ara_bleu_et_jaune_lieu.png", cond:"condition/ara_bleu_et_jaune_meteo.png", heure:"condition/ara_bleu_et_jaune_heure.png"},
    {name:"红绿金刚鹦鹉", bg:"condition/ara_rouge_et_vert_lieu.png", cond:"condition/ara_rouge_et_vert_meteo.png", heure:"condition/ara_rouge_et_vert_heure.png"},
    {name:"紫蓝金刚鹦鹉", bg:"condition/ara_indigo_lieu.png", cond:"condition/ara_indigo_meteo.png", heure:"condition/ara_indigo_heure.png"},
    {name:"白鹡鸰", bg:"condition/bergeronnette_grise_lieu.png", cond:"condition/bergeronnette_grise_meteo.png", heure:"condition/bergeronnette_grise_heure.png"},
    {name:"红腹灰雀", bg:"condition/bouvreuil_lieu.png", cond:"condition/bouvreuil_meteo.png", heure:"condition/bouvreuil_heure.png"},
    {name:"红腹灰雀", bg:"condition/bouvreuil_a_ventre_rouge_lieu.png", cond:"condition/bouvreuil_a_ventre_rouge_meteo.png", heure:"condition/bouvreuil_a_ventre_rouge_heure.png"},
    {name:"七彩唐纳雀", bg:"condition/calliste_septicolore_lieu.png", cond:"condition/calliste_septicolore_meteo.png", heure:"condition/calliste_septicolore_heure.png"},
    {name:"白头硬尾鸭", bg:"condition/canard_a_tete_blanche_lieu.png", cond:"condition/canard_a_tete_blanche_meteo.png", heure:"condition/canard_a_tete_blanche_heure.png"},
    {name:"绿头鸭", bg:"condition/canard_colvert_lieu.png", cond:"condition/canard_colvert_meteo.png", heure:"condition/canard_colvert_heure.png"},
    {name:"赤颈鸭", bg:"condition/canard_siffleur_lieu.png", cond:"condition/canard_siffleur_meteo.png", heure:"condition/canard_siffleur_heure.png"},
    {name:"灰冠主红雀", bg:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_lieu.png", cond:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_meteo.png", heure:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_heure.png"},
    {name:"粉头果鸠", bg:"condition/colombe_jambu_lieu.png", cond:"condition/colombe_jambu_meteo.png", heure:"condition/colombe_jambu_heure.png"},
    {name:"斑胸草雀", bg:"condition/diamant_mandarin_lieu.png", cond:"condition/diamant_mandarin_meteo.png", heure:"condition/diamant_mandarin_heure.png"},
    {name:"王绒鸭", bg:"condition/eider_royal_lieu.png", cond:"condition/eider_royal_meteo.png", heure:"condition/eider_royal_heure.png"},
    {name:"白腹锦鸡", bg:"condition/faisan_a_ventre_blanc_lieu.png", cond:"condition/faisan_a_ventre_blanc_meteo.png", heure:"condition/faisan_a_ventre_blanc_heure.png"},
    {name:"红脚隼", bg:"condition/faucon_a_pattes_rouges_lieu.png", cond:"condition/faucon_a_pattes_rouges_meteo.png", heure:"condition/faucon_a_pattes_rouges_heure.png"},
    {name:"游隼", bg:"condition/faucon_pelerin_lieu.png", cond:"condition/faucon_pelerin_meteo.png", heure:"condition/faucon_pelerin_heure.png"},
    {name:"红隼", bg:"condition/faucon_rouge_lieu.png", cond:"condition/faucon_rouge_meteo.png", heure:"condition/faucon_rouge_heure.png"},
    {name:"美洲红鹳", bg:"condition/flamant_rose_americain_lieu.png", cond:"condition/flamant_rose_americain_meteo.png", heure:"condition/flamant_rose_americain_heure.png"},
    {name:"苍头燕雀", bg:"condition/fringilla_coelebs_lieu.png", cond:"condition/fringilla_coelebs_meteo.png", heure:"condition/fringilla_coelebs_heure.png"},
    {name:"铜蓝鹟", bg:"condition/gobemouche_vertdegris_lieu.png", cond:"condition/gobemouche_vertdegris_meteo.png", heure:"condition/gobemouche_vertdegris_heure.png"},
    {name:"海鸥", bg:"condition/goeland_lieu.png", cond:"condition/goeland_meteo.png", heure:"condition/goeland_heure.png"},
    {name:"金黄鹂", bg:"condition/golden_oriole_lieu.png", cond:"condition/golden_oriole_meteo.png", heure:"condition/golden_oriole_heure.png"},
    {name:"雕鸮", bg:"condition/grand_duc_deurope_lieu.png", cond:"condition/grand_duc_deurope_meteo.png", heure:"condition/grand_duc_deurope_heure.png"},
    {name:"大红鹳", bg:"condition/grand_flamant_lieu.png", cond:"condition/grand_flamant_meteo.png", heure:"condition/grand_flamant_heure.png"},
    {name:"北美黑啄木鸟", bg:"condition/grand_pic_lieu.png", cond:"condition/grand_pic_meteo.png", heure:"condition/grand_pic_heure.png"},
    {name:"锡嘴雀", bg:"condition/grosbec_lieu.png", cond:"condition/grosbec_meteo.png", heure:"condition/grosbec_heure.png"},
    {name:"黄喉蜂虎", bg:"condition/guepier_deurope_lieu.png", cond:"condition/guepier_deurope_meteo.png", heure:"condition/guepier_deurope_heure.png"},
    {name:"斑头秋沙鸭", bg:"condition/harle_piette_lieu.png", cond:"condition/harle_piette_meteo.png", heure:"condition/harle_piette_heure.png"},
    {name:"长耳鸮", bg:"condition/hibou_moyen_duc_lieu.png", cond:"condition/hibou_moyen_duc_meteo.png", heure:"condition/hibou_moyen_duc_heure.png"},
    {name:"黄头亭鸟", bg:"condition/jardinier_a_tete_jaune_lieu.png", cond:"condition/jardinier_a_tete_jaune_meteo.png", heure:"condition/jardinier_a_tete_jaune_heure.png"},
    {name:"白腰朱顶雀", bg:"condition/linotte_a_dos_blanc_lieu.png", cond:"condition/linotte_a_dos_blanc_meteo.png", heure:"condition/linotte_a_dos_blanc_heure.png"},
    {name:"东蓝鸲", bg:"condition/merle_bleu_de_lest_lieu.png", cond:"condition/merle_bleu_de_lest_meteo.png", heure:"condition/merle_bleu_de_lest_heure.png"},
    {name:"银喉长尾山雀", bg:"condition/mesange_a_menton_argent_lieu.png", cond:"condition/mesange_a_menton_argent_meteo.png", heure:"condition/mesange_a_menton_argent_heure.png"},
    {name:"蓝山雀", bg:"condition/mesange_bleue_lieu.png", cond:"condition/mesange_bleue_meteo.png", heure:"condition/mesange_bleue_heure.png"},
    {name:"黄腹纹霸鹟", bg:"condition/moucherolle_a_ventre_jaune_lieu.png", cond:"condition/moucherolle_a_ventre_jaune_meteo.png", heure:"condition/moucherolle_a_ventre_jaune_heure.png"},
    {name:"红嘴鸥", bg:"condition/mouette_lieu.png", cond:"condition/mouette_meteo.png", heure:"condition/mouette_heure.png"},
    {name:"文须雀", bg:"condition/panure_a_moustache_lieu.png", cond:"condition/panure_a_moustache_meteo.png", heure:"condition/panure_a_moustache_heure.png"},
    {name:"白孔雀", bg:"condition/paon_blanc_lieu.png", cond:"condition/paon_blanc_meteo.png", heure:"condition/paon_blanc_heure.png"},
    {name:"蓝孔雀", bg:"condition/paon_bleu_lieu.png", cond:"condition/paon_bleu_meteo.png", heure:"condition/paon_bleu_heure.png"},
    {name:"黑孔雀", bg:"condition/paon_noir_lieu.png", cond:"condition/paon_noir_meteo.png", heure:"condition/paon_noir_heure.png"},
    {name:"绿孔雀", bg:"condition/paon_vert_lieu.png", cond:"condition/paon_vert_meteo.png", heure:"condition/paon_vert_heure.png"},
    {name:"小红鹳", bg:"condition/petit_flamant_lieu.png", cond:"condition/petit_flamant_meteo.png", heure:"condition/petit_flamant_heure.png"},
    {name:"林䳭伯劳", bg:"condition/piegrieche_a_tete_rousse_lieu.png", cond:"condition/piegrieche_a_tete_rousse_meteo.png", heure:"condition/piegrieche_a_tete_rousse_heure.png"},
    {name:"橙腹果鸠", bg:"condition/pigeon_aux_fruits_dor_lieu.png", cond:"condition/pigeon_aux_fruits_dor_meteo.png", heure:"condition/pigeon_aux_fruits_dor_heure.png"},
    {name:"黄眼鸽", bg:"condition/pigeon_aux_yeux_jaunes_lieu.png", cond:"condition/pigeon_aux_yeux_jaunes_meteo.png", heure:"condition/pigeon_aux_yeux_jaunes_heure.png"},
    {name:"欧鸽", bg:"condition/pigeon_colombin_lieu.png", cond:"condition/pigeon_colombin_meteo.png", heure:"condition/pigeon_colombin_heure.png"},
    {name:"翁加鸽", bg:"condition/pigeon_de_wonga_lieu.png", cond:"condition/pigeon_de_wonga_meteo.png", heure:"condition/pigeon_de_wonga_heure.png"},
    {name:"粉红鸽", bg:"condition/pigeon_rose_lieu.png", cond:"condition/pigeon_rose_meteo.png", heure:"condition/pigeon_rose_heure.png"},
    {name:"雀鸟", bg:"condition/pinson_lieu.png", cond:"condition/pinson_meteo.png", heure:"condition/pinson_heure.png"},
    {name:"知更鸟", bg:"condition/rougegorge_lieu.png", cond:"condition/rougegorge_meteo.png", heure:"condition/rougegorge_heure.png"},
    {name:"䴓", bg:"condition/sittelle_lieu.png", cond:"condition/sittelle_meteo.png", heure:"condition/sittelle_heure.png"},
    {name:"燕鸥", bg:"condition/sterne_lieu.png", cond:"condition/sterne_meteo.png", heure:"condition/sterne_heure.png"},
    {name:"白玄鸥", bg:"condition/sterne_blanche_lieu.png", cond:"condition/sterne_blanche_meteo.png", heure:"condition/sterne_blanche_heure.png"},
    {name:"赤麻鸭", bg:"condition/tadorne_casarca_lieu.png", cond:"condition/tadorne_casarca_meteo.png", heure:"condition/tadorne_casarca_heure.png"},
    {name:"灰头斑鸠", bg:"condition/tourterelle_a_tete_grise_lieu.png", cond:"condition/tourterelle_a_tete_grise_meteo.png", heure:"condition/tourterelle_a_tete_grise_heure.png"},
    {name:"灰斑鸠", bg:"condition/tourterelle_grise_lieu.png", cond:"condition/tourterelle_grise_meteo.png", heure:"condition/tourterelle_grise_heure.png"},
    {name:"珠颈斑鸠", bg:"condition/tourterelle_tigrine_lieu.png", cond:"condition/tourterelle_tigrine_meteo.png", heure:"condition/tourterelle_tigrine_heure.png"},
    {name:"鹪鹩", bg:"condition/troglodyte_lieu.png", cond:"condition/troglodyte_meteo.png", heure:"condition/troglodyte_heure.png"}
];

// 11. 测验
const QUIZ_DATA = [
    { q: "谁是村庄的买家?", o: ["小阿尔伯特", "Ka Ching", "埃里克"], a: 0 },
    { q: "在哪里可以找到刺盖太阳鱼?", o: ["平静海域", "森林湖", "极光河"], a: 0 },
    { q: "哪个NPC管理收藏品?", o: ["收藏家", "鲍勃", "马西莫"], a: 0 },
    { q: "什么天气会出现彩虹?", o: ["暴风雨", "雾", "雨后天晴"], a: 2 },
    { q: "渔夫村在哪里?", o: ["东北", "西南", "东"], a: 1 },
    { q: "长尾水青蛾是:", o: ["晨间活动", "日间活动", "夜间活动"], a: 2 },
    { q: "水豚住在哪里?", o: ["遗迹", "跳台", "海滩"], a: 0 },
    { q: "谁卖动物(狗)?", o: ["弗尼", "琼夫人", "安德鲁"], a: 1 },
    { q: "在哪里钓皇带鱼?", o: ["河流", "湖泊", "海洋"], a: 2 },
    { q: "温泉区在哪里?", o: ["北", "南", "西"], a: 0 },
    { q: "独角仙住在哪里?", o: ["东码头", "田野", "森林"], a: 0 },
    { q: "紫蓝金刚鹦鹉是:", o: ["鱼", "昆虫", "鸟"], a: 2 },
    { q: "蝴蝶鲤住在哪里?", o: ["淡水", "咸水", "草原湖"], a: 2 },
    { q: "NPC威尔在哪里?", o: ["海边", "山上", "森林里"], a: 0 },
    { q: "鱼类按钮是什么颜色?", o: ["绿色", "蓝色", "橙色"], a: 1 },
    { q: "熊蜂住在哪里?", o: ["湖泊", "花田", "洞穴"], a: 1 },
    { q: "水獭在哪里?", o: ["灯塔", "渔夫村", "遗迹"], a: 1 },
    { q: "熊猫住在哪里附近?", o: ["跳台", "村庄", "码头"], a: 0 },
    { q: "胡瓜鱼住在哪里?", o: ["草原湖", "上森林湖", "海洋"], a: 0 },
    { q: "安妮在哪里?", o: ["中央广场", "海滩", "森林"], a: 0 },
    { q: "羊驼住在哪里?", o: ["紫色海滩", "山", "河"], a: 0 },
    { q: "地图评分?", o: ["5", "0", "20"], a: 2 },
    { q: "蓝色贵族小龙虾住在哪里?", o: ["森林湖", "海洋", "平静海域"], a: 0 },
    { q: "鲸鱼山在哪里?", o: ["南", "北", "西"], a: 2 },
    { q: "Maptopia 的用途是:", o: ["卖东西", "定位资源", "代替游戏"], a: 1 },
    { q: "白鹡鸰是:", o: ["鸟", "鱼", "居民"], a: 1 },
    { q: "鹿住在哪里?", o: ["海滩", "橡树林", "城市"], a: 1 },
    { q: "钩粉蝶是:", o: ["水果", "昆虫", "鱼"], a: 1 },
    { q: "东码头在哪里?", o: ["北", "东", "南"], a: 1 },
    { q: "鲍勃是:", o: ["动物", "NPC", "地点"], a: 1 }
];
