// --- ข้อมูลภาษาไทย (data-thai.js) ---

// 1. ข้อความ UI (Interface)
const TEXTS = {
    title: "MAPTOPIA TH",
    enterBtn: "✨ เข้าสู่แผนที่ ✨",
    menu: {
        pnj: "NPC",
        animals: "สัตว์",
        bus: "รถบัส",
        shops: "ร้านค้า",
        places: "สถานที่",
        fish: "ปลา",
        bugs: "แมลง",
        birds: "นก",
        resources: "ทรัพยากร"
    },
    chat: {
        success: "✅ ส่งข้อความสำเร็จแล้ว!",
        error: "❌ เกิดข้อผิดพลาดในการส่ง",
        incomplete: "⚠️ กรุณากรอกข้อมูลให้ครบทุกช่อง",
        wait: "กำลังส่ง..."
    },
    quiz: {
        success: "✅ ถูกต้อง!",
        error: "❌ ผิด!",
        finishTitle: "🏆 ผู้เชี่ยวชาญตัวจริง!",
        finishText: "คุณรู้จัก Heartopia ดีเหมือนหลังมือตัวเองเลย",
        quitBtn: "ออกจากควิซ"
    },
    like: {
        thankyou: "ขอบคุณมาก!",
        already: "คุณโหวตไปแล้ว!"
    }
};

// 2. รายชื่อ NPC
const PNJ_DATA = [
    [-471, 501, "บ๊อบ", "pnj/bob.png"],
    [-526, 499, "อทารา", "pnj/atara.png"],
    [-478, 493, "นักสะสม", "pnj/collectioneur.png"],
    [-469, 488, "โดโรธี", "pnj/dorothée.png"],
    [-446, 493, "มัสซิโม", "pnj/massimo.png"],
    [-412, 418, "คาชิง", "pnj/ka ching.png"],
    [-399, 591, "แอนดรูว์", "pnj/andrew.png"],
    [-259, 522, "เอริค", "pnj/eric.png"],
    [-456, 549, "วาเนีย", "pnj/vanya.png"],
    [-502, 582, "นานิวะ", "pnj/naniwa.png"],
    [-502, 519, "คุณนายโจน", "pnj/mme joan.png"],
    [-807, 419, "วิลล์", "pnj/will.png"],
    [-355, 809, "แพตตี้", "pnj/patti.png"],
    [-653, 225, "เวอร์นี่", "pnj/vernie.png"],
    [-498, 526, "เบลีย์ เจ", "pnj/bayleyj.png"],
    [-528.3, 560.3, "บลอง", "pnj/blanc.png"],
    [-499.8, 499.0, "แอนนี่", "pnj/annie.png"],
    [-532.4, 634.8, "อัลเบิร์ต จูเนียร์", "pnj/albert jr.png"],
    [-734.8, 445.8, "บิลล์", "pnj/bill.png"],
    [-509.4, 414, "ดอริส (ฝน)", "pnj/doris.png"]
];

// 3. ป้ายรถบัส
const BUS_DATA = [
    ["ชานเมืองตะวันตก",[-533,340]], ["หมู่บ้านชานเมือง",[-519,639]], ["หมู่บ้านชาวประมง",[-654,479]], 
    ["ทุ่งดอกไม้",[-532,218]], ["ภูเขาบ่อน้ำพุร้อน",[-222,512]], ["ชานเมืองเหนือ",[-373,480]], 
    ["จัตุรัสกลาง",[-497,481]], ["ป่า",[-500,798]]
];

// 4. ร้านค้า
const SHOP_DATA = [
    [-472,487,"ร้านเสื้อผ้า","vetement.png"],[-474,503,"ร้านเฟอร์นิเจอร์","Meuble.png"],
    [-496.4,520.6,"ร้านขายสัตว์เลี้ยง","chien.png"],[-440,467,"ร้านหนังสือ","Librairie.png"]
];

// 5. สัตว์
const ANIMAL_DATA = [
    {pos: [-691, 783], name: "แพนด้า", img: "panda.png", radius: 60},
    {pos: [-184, 291], name: "คาปิบาร่า", img: "capybara.png", radius: 50},
    {pos: [-533, 340], name: "กระต่าย", img: "lapin.png", radius: 40},
    {pos: [-649, 185], name: "สุนัขจิ้งจอก", img: "renard.png", radius: 70},
    {pos: [-737, 512], name: "นาก", img: "loutre.png", radius: 40},
    {pos: [-354.3, 277.3], name: "มิงค์", img: "vison.png", radius: 10},
    {pos: [-531, 805], name: "กวาง", img: "cerf.png", radius: 60},
    {pos: [-725, 208], name: "ลามะ", img: "lama.png", radius: 50}
];

// 6. สถานที่
const LIEUX_DATA = [
    {pos:[-538,492], name:"จัตุรัสกลาง", type:"label-ville", startOn:true}, 
    {pos:[-692,506], name:"หมู่บ้านชาวประมง", type:"label-ville", startOn:true}, 
    {pos:[-438,513], name:"ถนนชาวเมือง", type:"label-ville", startOn:true}, 
    {pos:[-649,185], name:"ทุ่งดอกไม้", type:"label-ville", startOn:true}, 
    {pos:[-440,184], name:"ภูเขาปลาวาฬ", type:"label-ville", startOn:true}, 
    {pos:[-184,291], name:"ซากปรักหักพัง", type:"label-ville", startOn:true}, 
    {pos:[-223,501], name:"ภูเขาบ่อน้ำพุร้อน", type:"label-ville", startOn:true}, 
    {pos:[-228,627], name:"หน้าผาหิน", type:"label-ville", startOn:true}, 
    {pos:[-531,805], name:"ป่าโอ๊ค", type:"label-ville", startOn:true}, 
    {pos:[-494,429], name:"ถนนศิลปะ", type:"label-ville", startOn:true}, 
    {pos:[-510,558], name:"ถนนสวนดอกไม้", type:"label-ville", startOn:true}, 
    {pos:[-736,602], name:"ท่าเรือตะวันออก", type:"label-ville", startOn:true}, 
    {pos:[-690,402], name:"ท่าเทียบเรือ", type:"label-ville", startOn:true}, 
    {pos:[-780,387], name:"ประภาคาร", type:"label-ville", startOn:true}, 
    {pos:[-691,783], name:"กระดานกระโดดน้ำ", type:"label-ville", startOn:true}, 
    {pos:[-338,933], name:"เกาะในป่า", type:"label-ville", startOn:true}, 
    {pos:[-587,406], name:"ชานเมือง", type:"label-ville", startOn:true}, 
    {pos:[-725,208], name:"ชายหาดสีม่วง", type:"label-ville", startOn:true}, 
    {pos:[-783,478], name:"ทะเลสงบ", type:"label-eau", startOn:true}, 
    {pos:[-534,92], name:"ทะเลวาฬ", type:"label-eau", startOn:true}, 
    {pos:[-68,497], name:"ทะเลโบราณ", type:"label-eau", startOn:true}, 
    {pos:[-536,232], name:"ทะเลสาบทุ่งหญ้า", type:"label-eau", startOn:true}, 
    {pos:[-337,319], name:"แม่น้ำออโรร่า", type:"label-eau", startOn:true}, 
    {pos:[-176,394], name:"ทะเลสาบภูเขาไฟ", type:"label-eau", startOn:true}, 
    {pos:[-265,537], name:"ทะเลสาบบ่อน้ำพุร้อน", type:"label-eau", startOn:true}, 
    {pos:[-344,652], name:"แม่น้ำตื้น", type:"label-eau", startOn:true}, 
    {pos:[-598,748], name:"ทะเลสาบในป่า", type:"label-eau", startOn:true}, 
    {pos:[-431,774], name:"ทะเลสาบป่าตอนบน", type:"label-eau", startOn:true}, 
    {pos:[-608,481], name:"ทะเลสาบชานเมือง", type:"label-eau", startOn:true}, 
    {pos:[-669,368], name:"แม่น้ำเงียบสงบ", type:"label-eau", startOn:true}, 
    {pos:[-674,627], name:"แม่น้ำต้นไม้ยักษ์", type:"label-eau", startOn:true}, 
    {pos:[-600,600], name:"ทุ่งดอกไม้กังหันลม", type:"label-ville", startOn:true}, 
    {pos:[-670,450], name:"โป๊ะตะวันออก", type:"label-ville", startOn:true}
];

// 7. ทรัพยากร
const resourcesData = {
    "ราสเบอร์รี่": { icon: "resource/framboise.png", positions: [[-680.8, 330.9], [-668.5, 352.1], [-667.9, 268.5], [-648.3, 288.6], [-613.5, 317.4], [-602.8, 274.5], [-617.6, 211.6], [-571.5, 254.4], [-538.9, 208.6], [-527.8, 251.6], [-535.8, 288.3], [-503.1, 242.9], [-495, 222.4], [-453.8, 222.4], [-438.6, 246], [-395, 247.4], [-387.1, 269.5]] },
    "บลูเบอร์รี่": { icon: "resource/myrtille.png", positions: [[-642.9, 371.9], [-631.9, 368.4], [-628.5, 365.5], [-606.8, 350.3], [-602.5, 342.3], [-590.1, 334.1], [-575.6, 332.1], [-562.1, 330], [-544.9, 324.5], [-518.4, 320.3], [-515.9, 320.5], [-500.8, 321.1], [-479.3, 328.6], [-468.3, 320], [-437.3, 313.9], [-411.4, 311.4], [-400.3, 311.4], [-379.5, 304.1], [-327.4, 352], [-313.6, 339], [-328.6, 371.5], [-324.4, 389.3], [-297.9, 410.8], [-271.6, 395.4], [-319.9, 413.5], [-330.4, 421.6], [-333.4, 450], [-338.6, 468.6], [-297.4, 484.4], [-349, 489.4], [-356.5, 499.3], [-360.4, 526.4], [-355.5, 545.1], [-352.9, 565.9], [-316, 558.1], [-363.6, 578.4], [-365.3, 609], [-360.9, 628.1], [-343, 634], [-388, 655.4], [-400.9, 654.3], [-421.9, 656.4], [-444.1, 670.6], [-462.5, 654], [-476.8, 654.6], [-491.6, 656.3], [-506.4, 672.4], [-525.4, 688], [-542.6, 650], [-559.3, 644.9], [-575.6, 651], [-597.8, 643.8], [-604.8, 633.8], [-627.9, 619.4]] },
    "แอปเปิ้ล": { icon: "resource/pomme.png", positions: [[-356.3, 493], [-365.4, 560.1], [-362.4, 581], [-324.6, 570.1], [-296, 610.3], [-365.6, 619.5], [-362.8, 628.5], [-393.5, 654.8], [-420.6, 653.3], [-436.1, 665.4], [-444.4, 685.1], [-436.6, 697.5], [-458.4, 744.9], [-505, 677.3], [-494.5, 657], [-459.8, 653.6], [-530.1, 677.9], [-540.1, 648.6], [-592.8, 676.6], [-606.9, 634.1], [-629.3, 623]] },
    "ต้นไม้ใหญ่": { icon: "resource/grand arbre.png", positions: [[-612, 424.5], [-641.8, 369], [-351, 329.5], [-414.3, 337.1], [-396.3, 608.9], [-376.3, 624], [-616, 593.6], [-672.3, 642]] },
    "หิน": { icon: "resource/pierre.png", positions: [[-615.9, 316], [-641.5, 278.8], [-558.4, 257.4], [-535, 292], [-499.5, 241.1], [-466.8, 283.1], [-407.1, 244.1], [-284, 402.8], [-254.6, 367.9], [-309.4, 479.1], [-263, 466.6], [-289.1, 544.6], [-315.5, 567.9], [-298.6, 625.4], [-391.3, 726.9], [-443.6, 697], [-468.6, 733.8], [-519, 714.9], [-564.9, 732.8], [-605.1, 680.3], [-673.9, 684.1]] },
    "ส้ม": { icon: "resource/orange.png", positions: [[-650.1, 370.9], [-639.5, 372], [-607.3, 351.4], [-602.9, 343.5], [-588.6, 336.6], [-559.6, 329.5], [-542.1, 324.8], [-515, 319.5], [-470.5, 321], [-461.4, 271.5], [-410.8, 314], [-397.3, 310.1], [-310.9, 339.3], [-327.6, 373.9], [-324.9, 391.9], [-295.4, 411.1], [-330.4, 420.9], [-333.8, 452.9]] },
    "เห็ดพอร์ชินี": { icon: "resource/cépes de bordeaux.png", positions: [[-615, 796.9], [-620, 778.1], [-610.6, 759.9], [-634.9, 745.5], [-650, 773.5], [-639, 800.6], [-543.5, 776.3], [-523.6, 777], [-524.3, 818.9], [-479.9, 780.8], [-464.3, 775.6], [-472.1, 801], [-477.3, 825.8], [-438.4, 789.3], [-410.5, 776.8], [-404.1, 794.1], [-415.8, 799.1]] },
    "เห็ดทรัฟเฟิลดำ": { icon: "resource/truffes noires.png", positions: [[-358.1, 911.1], [-357.4, 926.1], [-340.4, 913.6], [-325.8, 920], [-342.1, 956.5], [-363.3, 961.8]] },
    "เห็ดหอม": { icon: "resource/Lentins du chene.png", positions: [[-772.3, 411.8], [-763.5, 397], [-736.8, 426.1], [-717.3, 446.8], [-705.8, 432.1], [-667.1, 462.5], [-666.6, 482.5], [-698.5, 491.8], [-698.3, 520.5], [-690.3, 542.6], [-686.4, 553.1], [-719.8, 546.6], [-724.8, 555.3], [-707.5, 575.9], [-714.9, 596.3]] },
    "เห็ดนางรม": { icon: "resource/pleurote.png", positions: [[-220.5, 355.3], [-207.5, 352.6], [-145.3, 303], [-162.5, 296], [-190.5, 294.3], [-210.3, 301.8], [-221.3, 310], [-214, 421.1], [-196.1, 428.4], [-174.4, 399.8], [-212.6, 470.8], [-232.5, 522.3], [-205.8, 512.4], [-194.9, 526.1], [-169, 510.6], [-167.9, 533.9], [-186, 547.6], [-189.3, 583.9]] }
};

// 8. รายชื่อปลา
const fishList = [
    {name:"ปลาซิวซ่า", bg:"condition/ablette_lieu.png", cond:"condition/ablette_meteo.png", heure:"condition/ablette_heure.png"},
    {name:"ปลาแมดซันฟิช", bg:"condition/acantharchus_pomotis_lieu.png", cond:"condition/acantharchus_pomotis_meteo.png", heure:"condition/acantharchus_pomotis_heure.png"},
    {name:"ปลาไหลยุโรป", bg:"condition/anguille_europeenne_lieu.png", cond:"condition/anguille_europeenne_meteo.png", heure:"condition/anguille_europeenne_heure.png"},
    {name:"ปลาคิลลี่ฟิชลายแถบ", bg:"condition/aphyosemion_striatum_lieu.png", cond:"condition/aphyosemion_striatum_meteo.png", heure:"condition/aphyosemion_striatum_heure.png"},
    {name:"ปลาบาร์เบล", bg:"condition/barbeau_lieu.png", cond:"condition/barbeau_meteo.png", heure:"condition/barbeau_heure.png"},
    {name:"ปลาบาร์เบลเล็ก", bg:"condition/barbillon_lieu.png", cond:"condition/barbillon_meteo.png", heure:"condition/barbillon_heure.png"},
    {name:"ปลาแองเกลอร์", bg:"condition/baudroie_lieu.png", cond:"condition/baudroie_meteo.png", heure:"condition/baudroie_heure.png"},
    {name:"ปูเสฉวน", bg:"condition/bernard_lhermite_lieu.png", cond:"condition/bernard_lhermite_meteo.png", heure:"condition/bernard_lhermite_heure.png"},
    {name:"ปลาเบลนนี่แม่น้ำ", bg:"condition/blennie_de_riviere_lieu.png", cond:"condition/blennie_de_riviere_meteo.png", heure:"condition/blennie_de_riviere_heure.png"},
    {name:"ปลาโบนิโต", bg:"condition/bonite_lieu.png", cond:"condition/bonite_meteo.png", heure:"condition/bonite_heure.png"},
    {name:"ปลาไพค์จุด", bg:"condition/brochet_tachete_lieu.png", cond:"condition/brochet_tachete_meteo.png", heure:"condition/brochet_tachete_heure.png"},
    {name:"ปลาลิ่นเงิน", bg:"condition/carpe_argente_lieu.png", cond:"condition/carpe_argente_meteo.png", heure:"condition/carpe_argente_heure.png"},
    {name:"ปลาคาร์ปยุโรป", bg:"condition/carpe_europeenne_lieu.png", cond:"condition/carpe_europeenne_meteo.png", heure:"condition/carpe_europeenne_heure.png"},
    {name:"ปลาคาร์ปหางยาว", bg:"condition/carpe_papillon_lieu.png", cond:"condition/carpe_papillon_meteo.png", heure:"condition/carpe_papillon_heure.png"},
    {name:"ปลาเฉา", bg:"condition/carpe_noire_lieu.png", cond:"condition/carpe_noire_meteo.png", heure:"condition/carpe_noire_heure.png"},
    {name:"ปลาบู่แม่น้ำ", bg:"condition/chabot_lieu.png", cond:"condition/chabot_meteo.png", heure:"condition/chabot_heure.png"},
    {name:"ปลาฉลามหนูเงิน", bg:"condition/chimere_argentee_lieu.png", cond:"condition/chimere_argentee_meteo.png", heure:"condition/chimere_argentee_heure.png"},
    {name:"ปลาทองโคเมท", bg:"condition/comete_coussut_lieu.png", cond:"condition/comete_coussut_meteo.png", heure:"condition/comete_coussut_heure.png"},
    {name:"ปูแม่น้ำ", bg:"condition/crabe_de_ruisseau_lieu.png", cond:"condition/crabe_de_ruisseau_meteo.png", heure:"condition/crabe_de_ruisseau_heure.png"},
    {name:"กุ้งทะเล", bg:"condition/crevette_de_la_mer_lieu.png", cond:"condition/crevette_de_la_mer_meteo.png", heure:"condition/crevette_de_la_mer_heure.png"},
    {name:"กุ้งเขียว", bg:"condition/crevette_verte_lieu.png", cond:"condition/crevette_verte_meteo.png", heure:"condition/crevette_verte_heure.png"},
    {name:"กุ้งเครย์ฟิชยุโรป", bg:"condition/ecrevisse_noble_lieu.png", cond:"condition/ecrevisse_noble_meteo.png", heure:"condition/ecrevisse_noble_heure.png"},
    {name:"กุ้งเครย์ฟิชน้ำเงิน", bg:"condition/ecrevisse_noble_bleue_lieu.png", cond:"condition/ecrevisse_noble_bleue_meteo.png", heure:"condition/ecrevisse_noble_bleue_heure.png"},
    {name:"ปลาแฮดด็อก", bg:"condition/eglefin_lieu.png", cond:"condition/eglefin_meteo.png", heure:"condition/eglefin_heure.png"},
    {name:"ปลาสมิลท์", bg:"condition/eperlan_lieu.png", cond:"condition/eperlan_meteo.png", heure:"condition/eperlan_heure.png"},
    {name:"ปลาไวท์ฟิช", bg:"condition/fera_lieu.png", cond:"condition/fera_meteo.png", heure:"condition/fera_heure.png"},
    {name:"ปลากะพงปากกว้าง", bg:"condition/grand_blackbasse_lieu.png", cond:"condition/grand_blackbasse_meteo.png", heure:"condition/grand_blackbasse_heure.png"},
    {name:"กบยุโรป", bg:"condition/grenouille_europeenne_lieu.png", cond:"condition/grenouille_europeenne_meteo.png", heure:"condition/grenouille_europeenne_heure.png"},
    {name:"ปลาบู่", bg:"condition/gobie_lieu.png", cond:"condition/gobie_meteo.png", heure:"condition/gobie_heure.png"},
    {name:"ปลาหัวแข็ง", bg:"condition/grondin_perlon_lieu.png", cond:"condition/grondin_perlon_meteo.png", heure:"condition/grondin_perlon_heure.png"},
    {name:"ม้าน้ำ", bg:"condition/hippocampe_lieu.png", cond:"condition/hippocampe_meteo.png", heure:"condition/hippocampe_heure.png"},
    {name:"ปลาแซลมอนดานูบ", bg:"condition/huchon_lieu.png", cond:"condition/huchon_meteo.png", heure:"condition/huchon_heure.png"},
    {name:"กุ้งมังกรยุโรป", bg:"condition/langouste_europeenne_lieu.png", cond:"condition/langouste_europeenne_meteo.png", heure:"condition/langouste_europeenne_heure.png"},
    {name:"ปลาหมูสี", bg:"condition/loche_des_fleurs_lieu.png", cond:"condition/loche_des_fleurs_meteo.png", heure:"condition/loche_des_fleurs_heure.png"},
    {name:"ปลาหมูหิน", bg:"condition/loche_des_rochers_lieu.png", cond:"condition/loche_des_rochers_meteo.png", heure:"condition/loche_des_rochers_heure.png"},
    {name:"ปลาเบอร์บอต", bg:"condition/lotte_lieu.png", cond:"condition/lotte_meteo.png", heure:"condition/lotte_heure.png"},
    {name:"ปลาแมคเคอเรล", bg:"condition/maquereau_atlantique_lieu.png", cond:"condition/maquereau_atlantique_meteo.png", heure:"condition/maquereau_atlantique_heure.png"},
    {name:"หอยแมลงภู่", bg:"condition/moule_lieu.png", cond:"condition/moule_meteo.png", heure:"condition/moule_heure.png"},
    {name:"ปลาอาร์กติกชาร์", bg:"condition/omble_chevalier_lieu.png", cond:"condition/omble_chevalier_meteo.png", heure:"condition/omble_chevalier_heure.png"},
    {name:"ปลาจิ้มฟันจระเข้", bg:"condition/ombrine_lieu.png", cond:"condition/ombrine_meteo.png", heure:"condition/ombrine_heure.png"},
    {name:"ปลาทรายแดง", bg:"condition/pagellus_bogaraveo_lieu.png", cond:"condition/pagellus_bogaraveo_meteo.png", heure:"condition/pagellus_bogaraveo_heure.png"},
    {name:"ปลากะพงขาว", bg:"condition/perche_de_mer_lieu.png", cond:"condition/perche_de_mer_meteo.png", heure:"condition/perche_de_mer_heure.png"},
    {name:"ปลาเพิร์ชพลัม", bg:"condition/perche_de_prunier_lieu.png", cond:"condition/perche_de_prunier_meteo.png", heure:"condition/perche_de_prunier_heure.png"},
    {name:"ปลาเพิร์ชแม่น้ำ", bg:"condition/perche_de_riviere_lieu.png", cond:"condition/perche_de_riviere_meteo.png", heure:"condition/perche_de_riviere_heure.png"},
    {name:"ปลาหมึกยักษ์", bg:"condition/pieuvre_lieu.png", cond:"condition/pieuvre_meteo.png", heure:"condition/pieuvre_heure.png"},
    {name:"ปลาหมึกยักษ์แคระ", bg:"condition/pieuvre_naine_atlantique_lieu.png", cond:"condition/pieuvre_naine_atlantique_meteo.png", heure:"condition/pieuvre_naine_atlantique_heure.png"},
    {name:"ปลาเสือ", bg:"condition/poissontigre_a_ventre_rouge_lieu.png", cond:"condition/poissontigre_a_ventre_rouge_meteo.png", heure:"condition/poissontigre_a_ventre_rouge_heure.png"},
    {name:"ปลาซีกเดียว", bg:"condition/plie_europeenne_lieu.png", cond:"condition/plie_europeenne_meteo.png", heure:"condition/plie_europeenne_heure.png"},
    {name:"ปลาการ์ตูน", bg:"condition/poissonclown_lieu.png", cond:"condition/poissonclown_meteo.png", heure:"condition/poissonclown_heure.png"},
    {name:"ปลาสติกเกิลแบ็ค", bg:"condition/poisson_epineux_lieu.png", cond:"condition/poisson_epineux_meteo.png", heure:"condition/poisson_epineux_heure.png"},
    {name:"ปลาปักเป้าแม่น้ำ", bg:"condition/poissonglobe_de_riviere_lieu.png", cond:"condition/poissonglobe_de_riviere_meteo.png", heure:"condition/poissonglobe_de_riviere_heure.png"},
    {name:"ปลาทอง", bg:"condition/poisson_rouge_lieu.png", cond:"condition/poisson_rouge_meteo.png", heure:"condition/poisson_rouge_heure.png"},
    {name:"ปลาดาบเงิน", bg:"condition/poisson_ruban_lieu.png", cond:"condition/poisson_ruban_meteo.png", heure:"condition/poisson_ruban_heure.png"},
    {name:"ปลาตาแดง", bg:"condition/poisson_a_yeux_rouges_lieu.png", cond:"condition/poisson_a_yeux_rouges_meteo.png", heure:"condition/poisson_a_yeux_rouges_heure.png"},
    {name:"ปลาออร์", bg:"condition/regalec_lieu.png", cond:"condition/regalec_meteo.png", heure:"condition/regalec_heure.png"},
    {name:"ปลาแพะแดง", bg:"condition/rouget_barbet_lieu.png", cond:"condition/rouget_barbet_meteo.png", heure:"condition/rouget_barbet_heure.png"},
    {name:"ปลาฉลามแมว", bg:"condition/roussette_lieu.png", cond:"condition/roussette_meteo.png", heure:"condition/roussette_heure.png"},
    {name:"ปลาแซนเดอร์ขาว", bg:"condition/sandre_blanc_lieu.png", cond:"condition/sandre_blanc_meteo.png", heure:"condition/sandre_blanc_heure.png"},
    {name:"ปลาแซลมอนแอตแลนติก", bg:"condition/saumon_atlantique_lieu.png", cond:"condition/saumon_atlantique_meteo.png", heure:"condition/saumon_atlantique_heure.png"},
    {name:"ปลาแซลมอนชุม", bg:"condition/saumon_keta_lieu.png", cond:"condition/saumon_keta_meteo.png", heure:"condition/saumon_keta_heure.png"},
    {name:"ปลาทูแขก", bg:"condition/saurel_lieu.png", cond:"condition/saurel_meteo.png", heure:"condition/saurel_heure.png"},
    {name:"ปลาซาร์ดีน", bg:"condition/sardine_lieu.png", cond:"condition/sardine_meteo.png", heure:"condition/sardine_heure.png"},
    {name:"ปลาหมึกกระดอง", bg:"condition/seiche_europeenne_lieu.png", cond:"condition/seiche_europeenne_meteo.png", heure:"condition/seiche_europeenne_heure.png"},
    {name:"ปลาดุกยุโรป", bg:"condition/silure_europeen_lieu.png", cond:"condition/silure_europeen_meteo.png", heure:"condition/silure_europeen_heure.png"},
    {name:"ปลาเทนช์ทอง", bg:"condition/tanche_doree_lieu.png", cond:"condition/tanche_doree_meteo.png", heure:"condition/tanche_doree_heure.png"},
    {name:"ลูกอ๊อด", bg:"condition/tetard_lieu.png", cond:"condition/tetard_meteo.png", heure:"condition/tetard_heure.png"},
    {name:"ปลานิล", bg:"condition/tilapia_lieu.png", cond:"condition/tilapia_meteo.png", heure:"condition/tilapia_heure.png"},
    {name:"ปลาเทอร์บอต", bg:"condition/turbot_lieu.png", cond:"condition/turbot_meteo.png", heure:"condition/turbot_heure.png"},
    {name:"ปลาซิว", bg:"condition/vairon_lieu.png", cond:"condition/vairon_meteo.png", heure:"condition/vairon_heure.png"},
    {name:"ปลาซิงเกิล", bg:"condition/zingel_streber_lieu.png", cond:"condition/zingel_streber_meteo.png", heure:"condition/zingel_streber_heure.png"}
];

// 9. รายชื่อแมลง
const bugList = [
    {name:"ผึ้งบัมเบิลบีหางขาว", bg:"condition/abeille_a_queue_blanche_lieu.png", cond:"condition/abeille_a_queue_blanche_meteo.png", heure:"condition/abeille_a_queue_blanche_heure.png"},
    {name:"ผึ้งไม้สีฟ้า", bg:"condition/Abeille_charpentière_bleue_lieu.png", cond:"condition/Abeille_charpentière_bleue_meteo.png", heure:"condition/Abeille_charpentière_bleue_heure.png"},
    {name:"ผึ้งไม้สีม่วง", bg:"condition/abeille_charpentiere_violette_lieu.png", cond:"condition/abeille_charpentiere_violette_meteo.png", heure:"condition/abeille_charpentiere_violette_heure.png"},
    {name:"ผีเสื้อกลางคืนหางยาว", bg:"condition/actias_neidhoederi_lieu.png", cond:"condition/actias_neidhoederi_meteo.png", heure:"condition/actias_neidhoederi_heure.png"},
    {name:"ผีเสื้อสีฟ้าพอร์ซเลน", bg:"condition/azure_de_porcelaine_lieu.png", cond:"condition/azure_de_porcelaine_meteo.png", heure:"condition/azure_de_porcelaine_heure.png"},
    {name:"ผึ้งบัมเบิลบี", bg:"condition/bourdon_lieu.png", cond:"condition/bourdon_meteo.png", heure:"condition/bourdon_heure.png"},
    {name:"ด้วงหนวดยาวลายเสือ", bg:"condition/capricorne_tigre_lieu.png", cond:"condition/capricorne_tigre_meteo.png", heure:"condition/capricorne_tigre_heure.png"},
    {name:"ด้วงดอกไม้สีฟ้า", bg:"condition/cetoine_etoilee_bleue_lieu.png", cond:"condition/cetoine_etoilee_bleue_meteo.png", heure:"condition/cetoine_etoilee_bleue_heure.png"},
    {name:"ด้วงดินสีเขียว", bg:"condition/cicindele_verte_lieu.png", cond:"condition/cicindele_verte_meteo.png", heure:"condition/cicindele_verte_heure.png"},
    {name:"จักจั่น", bg:"condition/cigale_lieu.png", cond:"condition/cigale_meteo.png", heure:"condition/cigale_heure.png"},
    {name:"ผีเสื้อสีเหลืองมะนาว", bg:"condition/citron_aspasia_lieu.png", cond:"condition/citron_aspasia_meteo.png", heure:"condition/citron_aspasia_heure.png"},
    {name:"เต่าทองเจ็ดจุด", bg:"condition/coccinelle_a_sept_points_lieu.png", cond:"condition/coccinelle_a_sept_points_meteo.png", heure:"condition/coccinelle_a_sept_points_heure.png"},
    {name:"เต่าทองเอเชีย", bg:"condition/coccinelle_asiatique_lieu.png", cond:"condition/coccinelle_asiatique_meteo.png", heure:"condition/coccinelle_asiatique_heure.png"},
    {name:"ด้วงหน่อไม้ฝรั่ง", bg:"condition/criocere_de_lasperge_lieu.png", cond:"condition/criocere_de_lasperge_meteo.png", heure:"condition/criocere_de_lasperge_heure.png"},
    {name:"ตั๊กแตนปีกตาข่าย", bg:"condition/criquet_a_ailes_reticulees_lieu.png", cond:"condition/criquet_a_ailes_reticulees_meteo.png", heure:"condition/criquet_a_ailes_reticulees_heure.png"},
    {name:"ตั๊กแตนขาโต", bg:"condition/criquet_aux_pattes_massives_lieu.png", cond:"condition/criquet_aux_pattes_massives_meteo.png", heure:"condition/criquet_aux_pattes_massives_heure.png"},
    {name:"มด", bg:"condition/fourmi_lieu.png", cond:"condition/fourmi_meteo.png", heure:"condition/fourmi_heure.png"},
    {name:"แมลงปอเข็มยักษ์", bg:"condition/grand_agrion_lieu.png", cond:"condition/grand_agrion_meteo.png", heure:"condition/grand_agrion_heure.png"},
    {name:"จิ้งหรีด", bg:"condition/grillon_lieu.png", cond:"condition/grillon_meteo.png", heure:"condition/grillon_heure.png"},
    {name:"แมลงปอหางขาว", bg:"condition/libellule_a_queue_blanche_lieu.png", cond:"condition/libellule_a_queue_blanche_meteo.png", heure:"condition/libellule_a_queue_blanche_heure.png"},
    {name:"แมลงปอลายจุด", bg:"condition/libellule_tachetee_lieu.png", cond:"condition/libellule_tachetee_meteo.png", heure:"condition/libellule_tachetee_heure.png"},
    {name:"ตั๊กแตนตำข้าวสีรุ้ง", bg:"condition/mante_arcenciel_lieu.png", cond:"condition/mante_arcenciel_meteo.png", heure:"condition/mante_arcenciel_heure.png"},
    {name:"ตั๊กแตนตำข้าวปาปัว", bg:"condition/mante_papoue_lieu.png", cond:"condition/mante_papoue_meteo.png", heure:"condition/mante_papoue_heure.png"},
    {name:"ผีเสื้อลายเสือดาว", bg:"condition/melitee_leopard_lieu.png", cond:"condition/melitee_leopard_meteo.png", heure:"condition/melitee_leopard_heure.png"},
    {name:"ผีเสื้อนกยูง", bg:"condition/paondujour_lieu.png", cond:"condition/paondujour_meteo.png", heure:"condition/paondujour_heure.png"},
    {name:"ผีเสื้อวงแหวนแดง", bg:"condition/papillon_a_anneaux_rouges_lieu.png", cond:"condition/papillon_a_anneaux_rouges_meteo.png", heure:"condition/papillon_a_anneaux_rouges_heure.png"},
    {name:"ผีเสื้อคอแดง", bg:"condition/papillon_a_col_rouge_lieu.png", cond:"condition/papillon_a_col_rouge_meteo.png", heure:"condition/papillon_a_col_rouge_heure.png"},
    {name:"ผีเสื้อขาว", bg:"condition/papillon_blanc_lieu.png", cond:"condition/papillon_blanc_meteo.png", heure:"condition/papillon_blanc_heure.png"},
    {name:"ผีเสื้อสีทอง", bg:"condition/papillon_dore_lieu.png", cond:"condition/papillon_dore_meteo.png", heure:"condition/papillon_dore_heure.png"},
    {name:"ผีเสื้อแม่มดขาว", bg:"condition/Papillon_sorcière_blanche_lieu.png", cond:"condition/Papillon_sorcière_blanche_meteo.png", heure:"condition/Papillon_sorcière_blanche_heure.png"},
    {name:"ผีเสื้ออะพอลโล", bg:"condition/parnassien_lieu.png", cond:"condition/parnassien_meteo.png", heure:"condition/parnassien_heure.png"},
    {name:"ผีเสื้อขาวเล็ก", bg:"condition/pieride_du_cresson_lieu.png", cond:"condition/pieride_du_cresson_meteo.png", heure:"condition/pieride_du_cresson_heure.png"},
    {name:"มวนปิกัสโซ่", bg:"condition/punaise_picasso_lieu.png", cond:"condition/punaise_picasso_meteo.png", heure:"condition/punaise_picasso_heure.png"},
    {name:"ด้วงสีแดง", bg:"condition/pyrochroa_lieu.png", cond:"condition/pyrochroa_meteo.png", heure:"condition/pyrochroa_heure.png"},
    {name:"มวนไฟ", bg:"condition/pyrrhocoris_apterus_lieu.png", cond:"condition/pyrrhocoris_apterus_meteo.png", heure:"condition/pyrrhocoris_apterus_heure.png"},
    {name:"ตั๊กแตนโอเอซิส", bg:"condition/sauterelle_de_loasis_lieu.png", cond:"condition/sauterelle_de_loasis_meteo.png", heure:"condition/sauterelle_de_loasis_heure.png"},
    {name:"ตั๊กแตนสีชมพู", bg:"condition/sauterelle_rose_lieu.png", cond:"condition/sauterelle_rose_meteo.png", heure:"condition/sauterelle_rose_heure.png"},
    {name:"ด้วงยูนิคอร์น", bg:"condition/scarabee_unicorne_lieu.png", cond:"condition/scarabee_unicorne_meteo.png", heure:"condition/scarabee_unicorne_heure.png"},
    {name:"ผีเสื้อจักรพรรดิสีม่วง", bg:"condition/Vanesse_violette_lieu.png", cond:"condition/Vanesse_violette_meteo.png", heure:"condition/Vanesse_violette_heure.png"}
];

// 10. รายชื่อนก
const birdList = [
    {name:"นกมาคอว์สีน้ำเงินเหลือง", bg:"condition/ara_bleu_et_jaune_lieu.png", cond:"condition/ara_bleu_et_jaune_meteo.png", heure:"condition/ara_bleu_et_jaune_heure.png"},
    {name:"นกมาคอว์สีแดงเขียว", bg:"condition/ara_rouge_et_vert_lieu.png", cond:"condition/ara_rouge_et_vert_meteo.png", heure:"condition/ara_rouge_et_vert_heure.png"},
    {name:"นกมาคอว์สีคราม", bg:"condition/ara_indigo_lieu.png", cond:"condition/ara_indigo_meteo.png", heure:"condition/ara_indigo_heure.png"},
    {name:"นกเด้าลมหลังเทา", bg:"condition/bergeronnette_grise_lieu.png", cond:"condition/bergeronnette_grise_meteo.png", heure:"condition/bergeronnette_grise_heure.png"},
    {name:"นกบุลฟินช์", bg:"condition/bouvreuil_lieu.png", cond:"condition/bouvreuil_meteo.png", heure:"condition/bouvreuil_heure.png"},
    {name:"นกบุลฟินช์ท้องแดง", bg:"condition/bouvreuil_a_ventre_rouge_lieu.png", cond:"condition/bouvreuil_a_ventre_rouge_meteo.png", heure:"condition/bouvreuil_a_ventre_rouge_heure.png"},
    {name:"นกแทนเนเจอร์เจ็ดสี", bg:"condition/calliste_septicolore_lieu.png", cond:"condition/calliste_septicolore_meteo.png", heure:"condition/calliste_septicolore_heure.png"},
    {name:"เป็ดหัวขาว", bg:"condition/canard_a_tete_blanche_lieu.png", cond:"condition/canard_a_tete_blanche_meteo.png", heure:"condition/canard_a_tete_blanche_heure.png"},
    {name:"เป็ดแมลลาร์ด", bg:"condition/canard_colvert_lieu.png", cond:"condition/canard_colvert_meteo.png", heure:"condition/canard_colvert_heure.png"},
    {name:"เป็ดวิเจน", bg:"condition/canard_siffleur_lieu.png", cond:"condition/canard_siffleur_meteo.png", heure:"condition/canard_siffleur_heure.png"},
    {name:"นกคาร์ดินัลหงอนเทา", bg:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_lieu.png", cond:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_meteo.png", heure:"condition/cardinal_a_couronne_grisecolombar_a_cou_rose_heure.png"},
    {name:"นกเปล้าหน้าชมพู", bg:"condition/colombe_jambu_lieu.png", cond:"condition/colombe_jambu_meteo.png", heure:"condition/colombe_jambu_heure.png"},
    {name:"นกม้าลาย", bg:"condition/diamant_mandarin_lieu.png", cond:"condition/diamant_mandarin_meteo.png", heure:"condition/diamant_mandarin_heure.png"},
    {name:"เป็ดไอเดอร์ราชวงศ์", bg:"condition/eider_royal_lieu.png", cond:"condition/eider_royal_meteo.png", heure:"condition/eider_royal_heure.png"},
    {name:"ไก่ฟ้าเลดี้แอมเฮิร์ต", bg:"condition/faisan_a_ventre_blanc_lieu.png", cond:"condition/faisan_a_ventre_blanc_meteo.png", heure:"condition/faisan_a_ventre_blanc_heure.png"},
    {name:"เหยี่ยวตีนแดง", bg:"condition/faucon_a_pattes_rouges_lieu.png", cond:"condition/faucon_a_pattes_rouges_meteo.png", heure:"condition/faucon_a_pattes_rouges_heure.png"},
    {name:"เหยี่ยวเพเรกริน", bg:"condition/faucon_pelerin_lieu.png", cond:"condition/faucon_pelerin_meteo.png", heure:"condition/faucon_pelerin_heure.png"},
    {name:"เหยี่ยวแดง", bg:"condition/faucon_rouge_lieu.png", cond:"condition/faucon_rouge_meteo.png", heure:"condition/faucon_rouge_heure.png"},
    {name:"นกฟลามิงโกอเมริกา", bg:"condition/flamant_rose_americain_lieu.png", cond:"condition/flamant_rose_americain_meteo.png", heure:"condition/flamant_rose_americain_heure.png"},
    {name:"นกจาบปีกอ่อนอกสีชมพู", bg:"condition/fringilla_coelebs_lieu.png", cond:"condition/fringilla_coelebs_meteo.png", heure:"condition/fringilla_coelebs_heure.png"},
    {name:"นกจับแมลงสีฟ้าอ่อน", bg:"condition/gobemouche_vertdegris_lieu.png", cond:"condition/gobemouche_vertdegris_meteo.png", heure:"condition/gobemouche_vertdegris_heure.png"},
    {name:"นกนางนวล", bg:"condition/goeland_lieu.png", cond:"condition/goeland_meteo.png", heure:"condition/goeland_heure.png"},
    {name:"นกขมิ้นทอง", bg:"condition/golden_oriole_lieu.png", cond:"condition/golden_oriole_meteo.png", heure:"condition/golden_oriole_heure.png"},
    {name:"นกเค้าแมวหูยาว", bg:"condition/grand_duc_deurope_lieu.png", cond:"condition/grand_duc_deurope_meteo.png", heure:"condition/grand_duc_deurope_heure.png"},
    {name:"นกฟลามิงโกใหญ่", bg:"condition/grand_flamant_lieu.png", cond:"condition/grand_flamant_meteo.png", heure:"condition/grand_flamant_heure.png"},
    {name:"นกหัวขวานใหญ่", bg:"condition/grand_pic_lieu.png", cond:"condition/grand_pic_meteo.png", heure:"condition/grand_pic_heure.png"},
    {name:"นกฮอว์ฟินช์", bg:"condition/grosbec_lieu.png", cond:"condition/grosbec_meteo.png", heure:"condition/grosbec_heure.png"},
    {name:"นกจาบคาโรป", bg:"condition/guepier_deurope_lieu.png", cond:"condition/guepier_deurope_meteo.png", heure:"condition/guepier_deurope_heure.png"},
    {name:"เป็ดปากยาว", bg:"condition/harle_piette_lieu.png", cond:"condition/harle_piette_meteo.png", heure:"condition/harle_piette_heure.png"},
    {name:"นกฮูกหูยาว", bg:"condition/hibou_moyen_duc_lieu.png", cond:"condition/hibou_moyen_duc_meteo.png", heure:"condition/hibou_moyen_duc_heure.png"},
    {name:"นกซุ้มหอยทอง", bg:"condition/jardinier_a_tete_jaune_lieu.png", cond:"condition/jardinier_a_tete_jaune_meteo.png", heure:"condition/jardinier_a_tete_jaune_heure.png"},
    {name:"นกลินเน็ตหัวขาว", bg:"condition/linotte_a_dos_blanc_lieu.png", cond:"condition/linotte_a_dos_blanc_meteo.png", heure:"condition/linotte_a_dos_blanc_heure.png"},
    {name:"นกบลูเบิร์ดตะวันออก", bg:"condition/merle_bleu_de_lest_lieu.png", cond:"condition/merle_bleu_de_lest_meteo.png", heure:"condition/merle_bleu_de_lest_heure.png"},
    {name:"นกตีทองคอเงิน", bg:"condition/mesange_a_menton_argent_lieu.png", cond:"condition/mesange_a_menton_argent_meteo.png", heure:"condition/mesange_a_menton_argent_heure.png"},
    {name:"นกตีทองสีฟ้า", bg:"condition/mesange_bleue_lieu.png", cond:"condition/mesange_bleue_meteo.png", heure:"condition/mesange_bleue_heure.png"},
    {name:"นกจับแมลงท้องเหลือง", bg:"condition/moucherolle_a_ventre_jaune_lieu.png", cond:"condition/moucherolle_a_ventre_jaune_meteo.png", heure:"condition/moucherolle_a_ventre_jaune_heure.png"},
    {name:"นกนางนวลหัวดำ", bg:"condition/mouette_lieu.png", cond:"condition/mouette_meteo.png", heure:"condition/mouette_heure.png"},
    {name:"นกกระจิบหนวด", bg:"condition/panure_a_moustache_lieu.png", cond:"condition/panure_a_moustache_meteo.png", heure:"condition/panure_a_moustache_heure.png"},
    {name:"นกยูงขาว", bg:"condition/paon_blanc_lieu.png", cond:"condition/paon_blanc_meteo.png", heure:"condition/paon_blanc_heure.png"},
    {name:"นกยูงอินเดีย", bg:"condition/paon_bleu_lieu.png", cond:"condition/paon_bleu_meteo.png", heure:"condition/paon_bleu_heure.png"},
    {name:"นกยูงดำ", bg:"condition/paon_noir_lieu.png", cond:"condition/paon_noir_meteo.png", heure:"condition/paon_noir_heure.png"},
    {name:"นกยูงไทย", bg:"condition/paon_vert_lieu.png", cond:"condition/paon_vert_meteo.png", heure:"condition/paon_vert_heure.png"},
    {name:"นกฟลามิงโกเล็ก", bg:"condition/petit_flamant_lieu.png", cond:"condition/petit_flamant_meteo.png", heure:"condition/petit_flamant_heure.png"},
    {name:"นกอีเสือหัวแดง", bg:"condition/piegrieche_a_tete_rousse_lieu.png", cond:"condition/piegrieche_a_tete_rousse_meteo.png", heure:"condition/piegrieche_a_tete_rousse_heure.png"},
    {name:"นกเปล้าท้องส้ม", bg:"condition/pigeon_aux_fruits_dor_lieu.png", cond:"condition/pigeon_aux_fruits_dor_meteo.png", heure:"condition/pigeon_aux_fruits_dor_heure.png"},
    {name:"นกพิราบตาเหลือง", bg:"condition/pigeon_aux_yeux_jaunes_lieu.png", cond:"condition/pigeon_aux_yeux_jaunes_meteo.png", heure:"condition/pigeon_aux_yeux_jaunes_heure.png"},
    {name:"นกพิราบป่า", bg:"condition/pigeon_colombin_lieu.png", cond:"condition/pigeon_colombin_meteo.png", heure:"condition/pigeon_colombin_heure.png"},
    {name:"นกพิราบวองก้า", bg:"condition/pigeon_de_wonga_lieu.png", cond:"condition/pigeon_de_wonga_meteo.png", heure:"condition/pigeon_de_wonga_heure.png"},
    {name:"นกพิราบชมพู", bg:"condition/pigeon_rose_lieu.png", cond:"condition/pigeon_rose_meteo.png", heure:"condition/pigeon_rose_heure.png"},
    {name:"นกจาบปีกอ่อน", bg:"condition/pinson_lieu.png", cond:"condition/pinson_meteo.png", heure:"condition/pinson_heure.png"},
    {name:"นกโรบิน", bg:"condition/rougegorge_lieu.png", cond:"condition/rougegorge_meteo.png", heure:"condition/rougegorge_heure.png"},
    {name:"นกไต่ไม้", bg:"condition/sittelle_lieu.png", cond:"condition/sittelle_meteo.png", heure:"condition/sittelle_heure.png"},
    {name:"นกนางนวลแกลบ", bg:"condition/sterne_lieu.png", cond:"condition/sterne_meteo.png", heure:"condition/sterne_heure.png"},
    {name:"นกนางนวลแกลบขาว", bg:"condition/sterne_blanche_lieu.png", cond:"condition/sterne_blanche_meteo.png", heure:"condition/sterne_blanche_heure.png"},
    {name:"เป็ดพม่า", bg:"condition/tadorne_casarca_lieu.png", cond:"condition/tadorne_casarca_meteo.png", heure:"condition/tadorne_casarca_heure.png"},
    {name:"นกเขาหัวเทา", bg:"condition/tourterelle_a_tete_grise_lieu.png", cond:"condition/tourterelle_a_tete_grise_meteo.png", heure:"condition/tourterelle_a_tete_grise_heure.png"},
    {name:"นกเขาแขก", bg:"condition/tourterelle_grise_lieu.png", cond:"condition/tourterelle_grise_meteo.png", heure:"condition/tourterelle_grise_heure.png"},
    {name:"นกเขาชวา", bg:"condition/tourterelle_tigrine_lieu.png", cond:"condition/tourterelle_tigrine_meteo.png", heure:"condition/tourterelle_tigrine_heure.png"},
    {name:"นกกระจิบหญ้า", bg:"condition/troglodyte_lieu.png", cond:"condition/troglodyte_meteo.png", heure:"condition/troglodyte_heure.png"}
];

// 11. ควิซ (Quiz)
const QUIZ_DATA = [
    { q: "ใครคือผู้รับซื้อประจำหมู่บ้าน?", o: ["อัลเบิร์ต จูเนียร์", "คาชิง", "เอริค"], a: 0 },
    { q: "คุณสามารถพบปลาแมดซันฟิชได้ที่ไหน?", o: ["ทะเลสงบ", "ทะเลสาบในป่า", "แม่น้ำออโรร่า"], a: 0 },
    { q: "NPC คนไหนเป็นคนจัดการของสะสม?", o: ["นักสะสม", "บ๊อบ", "มัสซิโม"], a: 0 },
    { q: "สภาพอากาศแบบไหนที่จะทำให้เกิดรุ้งกินน้ำ?", o: ["พายุ", "หมอก", "แดดออกหลังฝนตก"], a: 2 },
    { q: "หมู่บ้านชาวประมงตั้งอยู่ที่ไหน?", o: ["ตะวันออกเฉียงเหนือ", "ตะวันตกเฉียงใต้", "ตะวันออก"], a: 1 },
    { q: "ผีเสื้อกลางคืนหางยาวจะปรากฏตัวเมื่อไหร่?", o: ["เช้า", "กลางวัน", "กลางคืน"], a: 2 },
    { q: "คาปิบาร่าอาศัยอยู่ที่ไหน?", o: ["ซากปรักหักพัง", "กระดานกระโดดน้ำ", "ชายหาด"], a: 0 },
    { q: "ใครเป็นคนขายสัตว์ (สุนัข)?", o: ["เวอร์นี่", "คุณนายโจน", "แแอนดรูว์"], a: 1 },
    { q: "ปลาออร์สามารถจับได้ที่ไหน?", o: ["แม่น้ำ", "ทะเลสาบ", "ทะเล"], a: 2 },
    { q: "เขตบ่อน้ำพุร้อนอยู่ที่ไหน?", o: ["ทิศเหนือ", "ทิศใต้", "ทิศตะวันตก"], a: 0 },
    { q: "ด้วงยูนิคอร์นอาศัยอยู่ที่ไหน?", o: ["ท่าเรือตะวันออก", "ทุ่งหญ้า", "ป่า"], a: 0 },
    { q: "นกมาคอว์สีครามคืออะไร?", o: ["ปลา", "แมลง", "นก"], a: 2 },
    { q: "ปลาคาร์ปหางยาวอาศัยอยู่ที่ไหน?", o: ["น้ำจืด", "น้ำเค็ม", "ทะเลสาบทุ่งหญ้า"], a: 2 },
    { q: "NPC วิลล์อยู่ที่ไหน?", o: ["ริมทะเล", "บนภูเขา", "ในป่า"], a: 0 },
    { q: "ปุ่ม 'ปลา' มีสีอะไร?", o: ["เขียว", "น้ำเงิน", "ส้ม"], a: 1 },
    { q: "ผึ้งบัมเบิลบีอาศัยอยู่ที่ไหน?", o: ["ทะเลสาบ", "ทุ่งดอกไม้", "ถ้ำ"], a: 1 },
    { q: "นากสามารถพบได้ที่ไหน?", o: ["ประภาคาร", "หมู่บ้านชาวประมง", "ซากปรักหักพัง"], a: 1 },
    { q: "แพนด้าอาศัยอยู่ใกล้กับอะไร?", o: ["กระดานกระโดดน้ำ", "หมู่บ้าน", "ท่าเรือ"], a: 0 },
    { q: "ปลาสมิลท์อาศัยอยู่ที่ไหน?", o: ["ทะเลสาบทุ่งหญ้า", "ทะเลสาบป่าตอนบน", "ทะเล"], a: 0 },
    { q: "แอนนี่อยู่ที่ไหน?", o: ["จัตุรัสกลาง", "ชายหาด", "ป่า"], a: 0 },
    { q: "ลามะอาศัยอยู่ที่ไหน?", o: ["ชายหาดสีม่วง", "ภูเขา", "แม่น้ำ"], a: 0 },
    { q: "คะแนนเต็ม 20 ของแผนที่นี้คือ?", o: ["5", "0", "20"], a: 2 },
    { q: "กุ้งเครย์ฟิชน้ำเงินอาศัยอยู่ที่ไหน?", o: ["ทะเลสาบในป่า", "ทะเล", "ทะเลสงบ"], a: 0 },
    { q: "ภูเขาปลาวาฬอยู่ที่ไหน?", o: ["ทิศใต้", "ทิศเหนือ", "ทิศตะวันตก"], a: 2 },
    { q: "Maptopia มีไว้เพื่ออะไร?", o: ["ขายไอเทม", "ระบุตำแหน่งทรัพยากร", "ใช้เล่นแทนเกม"], a: 1 },
    { q: "นกเด้าลมหลังเทาคืออะไร?", o: ["นก", "ปลา", "ผู้อยู่อาศัย"], a: 1 },
    { q: "กวางอาศัยอยู่ที่ไหน?", o: ["ชายหาด", "ป่าโอ๊ค", "เมือง"], a: 1 },
    { q: "ผีเสื้อสีเหลืองมะนาวคืออะไร?", o: ["ผลไม้", "แมลง", "ปลา"], a: 1 },
    { q: "ท่าเรือตะวันออกอยู่ที่ไหน?", o: ["ทิศเหนือ", "ทิศตะวันออก", "ทิศใต้"], a: 1 },
    { q: "บ๊อบคืออะไร?", o: ["สัตว์", "NPC", "สถานที่"], a: 1 }
];
